import type {
  DataSourceConfig,
  ExportOption,
  ReportCapabilityGroup,
  ReportField,
  ReportRow,
  ReportSettings,
  RequirementPhase,
} from './types'

export const defaultDataSourceConfig: DataSourceConfig = {
  kind: 'sample',
  name: '销售订单样例数据',
  credentialId: undefined,
  method: 'GET',
  endpoint: '/api/orders',
  dataPath: 'data',
  queryParams: '',
  headers: '',
  body: '',
  rawJson: '',
  sqlDatabase: '',
  sqlDriver: 'mysql',
  sqlHost: '',
  sqlPassword: '',
  sqlPort: '3306',
  sqlText: 'select * from sales_orders where order_date >= :startDate',
  sqlUsername: '',
}

export const defaultReportSettings: ReportSettings = {
  title: '销售订单导出报表',
  subtitle: '按客户、区域、订单状态和金额生成可导出的业务明细',
  fileName: 'sales-order-report',
  sheetName: '订单明细',
  templateType: 'detail',
  theme: 'default',
  density: 'standard',
  showIndex: true,
  showSummary: true,
  showFooter: true,
  watermark: 'Internal',
  previewLimit: 50,
  paperSize: 'A4',
  orientation: 'portrait',
  marginTop: 16,
  marginRight: 14,
  marginBottom: 16,
  marginLeft: 14,
  pageHeader: '销售订单导出报表',
  pageFooter: '第 {page} 页 / 共 {pages} 页',
  repeatTableHeader: true,
  permissionMode: 'inherit',
  asyncExportThreshold: 100000,
  streamExportThreshold: 1000000,
}

export const sampleRows: ReportRow[] = [
  {
    orderNo: 'SO-2026-0601',
    customer: '华东渠道中心',
    region: '华东',
    owner: '周明',
    orderDate: '2026-06-01',
    status: '已完成',
    enabledFlag: 1,
    quantity: 18,
    amount: 128600,
    grossMargin: 0.218,
  },
  {
    orderNo: 'SO-2026-0602',
    customer: '北区直营客户',
    region: '华北',
    owner: '陈露',
    orderDate: '2026-06-01',
    status: '待发货',
    enabledFlag: 1,
    quantity: 12,
    amount: 76400,
    grossMargin: 0.174,
  },
  {
    orderNo: 'SO-2026-0603',
    customer: '南方零售网络',
    region: '华南',
    owner: '李航',
    orderDate: '2026-06-02',
    status: '已完成',
    enabledFlag: 1,
    quantity: 26,
    amount: 188900,
    grossMargin: 0.246,
  },
  {
    orderNo: 'SO-2026-0604',
    customer: '西南项目部',
    region: '西南',
    owner: '赵颖',
    orderDate: '2026-06-02',
    status: '审批中',
    enabledFlag: 0,
    quantity: 9,
    amount: 53400,
    grossMargin: 0.139,
  },
  {
    orderNo: 'SO-2026-0605',
    customer: '华中分销联盟',
    region: '华中',
    owner: '王珂',
    orderDate: '2026-06-03',
    status: '已完成',
    enabledFlag: 1,
    quantity: 31,
    amount: 214300,
    grossMargin: 0.263,
  },
  {
    orderNo: 'SO-2026-0606',
    customer: '东北大客户部',
    region: '东北',
    owner: '刘宁',
    orderDate: '2026-06-03',
    status: '待收款',
    enabledFlag: 0,
    quantity: 15,
    amount: 97900,
    grossMargin: 0.191,
  },
  {
    orderNo: 'SO-2026-0607',
    customer: '海外事业组',
    region: '海外',
    owner: '孙悦',
    orderDate: '2026-06-04',
    status: '已完成',
    enabledFlag: 1,
    quantity: 22,
    amount: 302800,
    grossMargin: 0.312,
  },
  {
    orderNo: 'SO-2026-0608',
    customer: '电商旗舰店',
    region: '线上',
    owner: '高远',
    orderDate: '2026-06-04',
    status: '待发货',
    enabledFlag: 1,
    quantity: 44,
    amount: 169500,
    grossMargin: 0.152,
  },
]

export const defaultFields: ReportField[] = [
  {
    key: 'orderNo',
    label: '订单号',
    type: 'string',
    enabled: true,
    width: 150,
    align: 'left',
    summary: 'count',
  },
  {
    key: 'customer',
    label: '客户',
    type: 'string',
    enabled: true,
    width: 190,
    align: 'left',
    summary: 'none',
  },
  {
    key: 'region',
    label: '区域',
    type: 'string',
    enabled: true,
    width: 90,
    align: 'center',
    summary: 'none',
  },
  {
    key: 'owner',
    label: '负责人',
    type: 'string',
    enabled: true,
    width: 90,
    align: 'center',
    summary: 'none',
  },
  {
    key: 'orderDate',
    label: '订单日期',
    type: 'date',
    enabled: true,
    width: 120,
    align: 'center',
    summary: 'none',
  },
  {
    key: 'status',
    label: '状态',
    type: 'string',
    enabled: true,
    width: 100,
    align: 'center',
    summary: 'none',
  },
  {
    key: 'enabledFlag',
    label: '启用状态',
    type: 'string',
    enabled: true,
    width: 96,
    align: 'center',
    summary: 'none',
    mappingEnabled: true,
    mappingMode: 'manual',
    mappingItems: [
      { key: '1', label: '开启' },
      { key: '0', label: '关闭' },
    ],
  },
  {
    key: 'quantity',
    label: '数量',
    type: 'number',
    enabled: true,
    width: 90,
    align: 'right',
    summary: 'sum',
  },
  {
    key: 'amount',
    label: '销售额',
    type: 'currency',
    enabled: true,
    width: 130,
    align: 'right',
    summary: 'sum',
  },
  {
    key: 'grossMargin',
    label: '毛利率',
    type: 'percent',
    enabled: true,
    width: 100,
    align: 'right',
    summary: 'avg',
  },
]

export const exportOptions: ExportOption[] = [
  {
    format: 'csv',
    label: 'CSV',
    icon: 'i-lucide:file-text',
    description: '适合大批量明细导出，文件轻，兼容性高。',
  },
  {
    format: 'xls',
    label: 'Excel',
    icon: 'i-lucide:file-spreadsheet',
    description: '用 HTML-XLS 生成带样式的客户端 Excel 文件。',
  },
  {
    format: 'json',
    label: 'JSON',
    icon: 'i-lucide:braces',
    description: '保留模板、字段和数据，适合调试或二次集成。',
  },
  {
    format: 'pdf',
    label: 'PDF',
    icon: 'i-lucide:file-type-2',
    description: '打开分页打印预览，可保存为 PDF，服务端 PDF 可后续接入。',
  },
  {
    format: 'print',
    label: '打印',
    icon: 'i-lucide:printer',
    description: '按纸张和页边距设置打开浏览器打印窗口。',
  },
]

export const requirementPhases: RequirementPhase[] = [
  {
    phase: 'P0',
    title: '先闭环',
    items: ['数据源加载', '字段配置', '在线预览', '客户端导出'],
  },
  {
    phase: 'P1',
    title: '数据加工',
    items: ['请求参数', '过滤排序', '计算字段', '模板保存'],
  },
  {
    phase: 'P2',
    title: '企业化',
    items: ['权限审计', '版本回滚', '插件组件', '服务端兜底'],
  },
]

export const enterpriseCapabilityGroups: ReportCapabilityGroup[] = [
  {
    title: '数据建模',
    description: '面向 REST、SQL、JSON 和多数据集绑定的建模能力。',
    icon: 'i-lucide:database',
    items: [
      {
        label: '多数据源配置',
        description:
          '已支持样例、REST、JSON、SQL 配置，后续需要服务端连接池与鉴权。',
        icon: 'i-lucide:plug-zap',
        status: 'partial',
      },
      {
        label: '数据集与字段推断',
        description: '可根据返回数据推断字段，并保留字段排序、格式化和映射。',
        icon: 'i-lucide:columns-3',
        status: 'ready',
      },
      {
        label: '参数化查询',
        description:
          'Schema 已预留参数结构，下一步应接入参数面板和运行时注入。',
        icon: 'i-lucide:sliders-horizontal',
        status: 'planned',
      },
    ],
  },
  {
    title: '版式与打印',
    description: '覆盖明细表、单据、标签、分页打印和页眉页脚。',
    icon: 'i-lucide:printer',
    items: [
      {
        label: '纸张与页边距',
        description: '模板设置支持纸张、方向和四边页边距，打印时会写入 @page。',
        icon: 'i-lucide:file-output',
        status: 'ready',
      },
      {
        label: '页眉页脚',
        description:
          '已可配置页眉页脚文案，复杂分页变量应由服务端 PDF 引擎增强。',
        icon: 'i-lucide:panel-top',
        status: 'partial',
      },
      {
        label: '复杂报表版式',
        description: '主从、分组、交叉和自由画布属于后续布局引擎能力。',
        icon: 'i-lucide:layout-template',
        status: 'planned',
      },
    ],
  },
  {
    title: '导出链路',
    description: '兼顾客户端轻量导出和服务端异步任务。',
    icon: 'i-lucide:download',
    items: [
      {
        label: 'CSV/Excel/JSON',
        description: '客户端导出已闭环；大数据量应切换流式 CSV 或异步任务。',
        icon: 'i-lucide:file-spreadsheet',
        status: 'ready',
      },
      {
        label: 'PDF/打印',
        description:
          '当前使用浏览器打印，生产环境建议接 wkhtmltopdf、Playwright 或服务端 PDF。',
        icon: 'i-lucide:file-type-2',
        status: 'partial',
      },
      {
        label: '百万行异步导出',
        description: 'Schema 已暴露阈值，后续由下载中心和任务中心承接。',
        icon: 'i-lucide:server-cog',
        status: 'planned',
      },
    ],
  },
  {
    title: '治理与协作',
    description: '企业模板要可控、可审计、可回滚。',
    icon: 'i-lucide:shield-check',
    items: [
      {
        label: '模板快照',
        description: '已支持本地模板快照，后续应迁移到服务端版本库。',
        icon: 'i-lucide:history',
        status: 'partial',
      },
      {
        label: '权限模式',
        description: '模板设置已暴露继承、模板级、私有模式，用于对接 RBAC。',
        icon: 'i-lucide:lock-keyhole',
        status: 'partial',
      },
      {
        label: '审计与发布流',
        description: '生产版本需要草稿、审批、发布、回滚和操作日志。',
        icon: 'i-lucide:route',
        status: 'planned',
      },
    ],
  },
]
