import type { ArticleItem } from './types'

export const articleItems: ArticleItem[] = [
  {
    id: 'doc-product-roadmap',
    title: '产品发布说明',
    summary: '整理版本重点、风险提示和上线检查项，供产品与研发团队协同确认。',
    category: '产品动态',
    tags: ['产品', '发布', '版本'],
    author: { name: '林屿', department: '产品中心' },
    createdAt: '2026-05-26 09:40',
    updatedAt: '2026-08-06 16:20',
    status: 'draft',
    views: 846,
    wordCount: 2180,
    icon: 'i-lucide:rocket',
    iconBackground: '#DBEAFE',
  },
  {
    id: 'doc-weekly',
    title: '运营周报模板',
    summary: '沉淀核心指标、渠道表现和行动计划，让团队周报保持统一结构。',
    category: '运营方法',
    tags: ['运营', '模板', '数据'],
    author: { name: '周然', department: '增长运营' },
    createdAt: '2026-05-20 14:16',
    updatedAt: '2026-08-06 11:08',
    status: 'published',
    views: 4256,
    wordCount: 1640,
    icon: 'i-lucide:chart-no-axes-combined',
    iconBackground: '#DCFCE7',
  },
  {
    id: 'doc-meeting',
    title: '项目复盘纪要',
    summary: '记录项目阶段结论、风险根因和后续负责人，形成可追踪的改进项。',
    category: '团队协作',
    tags: ['项目', '复盘', '协作'],
    author: { name: '陈晓', department: '平台研发' },
    createdAt: '2026-05-18 16:05',
    updatedAt: '2026-08-05 18:36',
    status: 'draft',
    views: 632,
    wordCount: 980,
    icon: 'i-lucide:notebook-tabs',
    iconBackground: '#EDE9FE',
  },
  {
    id: 'doc-design-system',
    title: '后台设计系统实践',
    summary: '从主题变量、组件边界和交互反馈三个维度建立一致的后台体验。',
    category: '设计研发',
    tags: ['设计系统', 'Vue', '规范'],
    author: { name: '许宁', department: '体验设计' },
    createdAt: '2026-06-12 10:30',
    updatedAt: '2026-08-04 15:42',
    status: 'published',
    views: 3189,
    wordCount: 3560,
    icon: 'i-lucide:palette',
    iconBackground: '#FCE7F3',
  },
  {
    id: 'doc-ai-governance',
    title: '企业 AI 应用治理清单',
    summary: '覆盖模型接入、数据权限、内容安全和审计回滚的上线检查清单。',
    category: 'AI 实践',
    tags: ['AI', '治理', '安全'],
    author: { name: '顾言', department: '技术委员会' },
    createdAt: '2026-06-28 13:50',
    updatedAt: '2026-08-03 09:18',
    status: 'published',
    views: 5870,
    wordCount: 4210,
    icon: 'i-lucide:shield-check',
    iconBackground: '#CCFBF1',
  },
  {
    id: 'doc-customer-story',
    title: '客户增长案例拆解',
    summary: '拆解客户从线索识别到续费增长的关键动作与指标变化。',
    category: '客户案例',
    tags: ['客户', '增长', '案例'],
    author: { name: '王若溪', department: '客户成功' },
    createdAt: '2026-07-05 11:24',
    updatedAt: '2026-08-02 17:55',
    status: 'draft',
    views: 412,
    wordCount: 2750,
    icon: 'i-lucide:users-round',
    iconBackground: '#FFEDD5',
  },
  {
    id: 'doc-release-checklist',
    title: '前端发布检查清单',
    summary: '汇总类型检查、路由验证、性能预算和回滚预案等发布前动作。',
    category: '工程效能',
    tags: ['前端', '发布', '质量'],
    author: { name: '沈牧', department: '工程效率' },
    createdAt: '2026-07-16 09:12',
    updatedAt: '2026-08-01 14:26',
    status: 'published',
    views: 2654,
    wordCount: 1890,
    icon: 'i-lucide:list-checks',
    iconBackground: '#E0E7FF',
  },
  {
    id: 'doc-data-security',
    title: '数据权限设计备忘',
    summary: '记录字段权限、数据范围和敏感信息脱敏方案的阶段性决策。',
    category: '技术方案',
    tags: ['权限', '数据', '架构'],
    author: { name: '赵敏', department: '架构组' },
    createdAt: '2026-04-22 15:40',
    updatedAt: '2026-07-28 10:16',
    status: 'archived',
    views: 1206,
    wordCount: 3120,
    icon: 'i-lucide:database-zap',
    iconBackground: '#FEE2E2',
  },
]
