import type {
  WorkflowAlert,
  WorkflowDefinition,
  WorkflowLatencyRank,
  WorkflowRunInstance,
  WorkflowRunStatus,
  WorkflowRunStep,
  WorkflowThroughputPoint,
} from './types'

const owners = {
  chen: { id: 'u-chen', name: '陈墨', department: '智能应用组' },
  lin: { id: 'u-lin', name: '林晓', department: '客户体验部' },
  qiao: { id: 'u-qiao', name: '乔安', department: '数据平台组' },
  shen: { id: 'u-shen', name: '沈嘉', department: '业务中台组' },
}

export const initialWorkflowDefinitions: WorkflowDefinition[] = [
  {
    id: 'wf-customer-service',
    name: '智能客服自动化',
    description: '知识库召回、回答生成、质量判断与人工工单协同。',
    category: '客户服务',
    status: 'published',
    version: 'v2.6.0',
    icon: 'i-lucide:headset',
    owner: owners.lin,
    trigger: '消息事件',
    nodeCount: 7,
    runCount: 18642,
    successRate: 98.7,
    averageDuration: '2.4s',
    createdAt: '2026-05-18 10:24',
    updatedAt: '2026-08-04 09:18',
    lastRunAt: '2 分钟前',
  },
  {
    id: 'wf-lead-routing',
    name: '销售线索智能分配',
    description: '识别客户意向、计算线索评分并分配给合适的销售团队。',
    category: '销售运营',
    status: 'published',
    version: 'v1.9.3',
    icon: 'i-lucide:route',
    owner: owners.shen,
    trigger: 'Webhook',
    nodeCount: 11,
    runCount: 9821,
    successRate: 96.4,
    averageDuration: '4.8s',
    createdAt: '2026-04-07 14:30',
    updatedAt: '2026-08-03 17:42',
    lastRunAt: '8 分钟前',
  },
  {
    id: 'wf-weekly-report',
    name: '运营周报生成',
    description: '汇总核心指标、定位异常波动并生成可执行的运营周报。',
    category: '数据分析',
    status: 'published',
    version: 'v3.1.1',
    icon: 'i-lucide:chart-no-axes-combined',
    owner: owners.qiao,
    trigger: '定时任务',
    nodeCount: 14,
    runCount: 634,
    successRate: 99.2,
    averageDuration: '18.6s',
    createdAt: '2026-02-21 09:10',
    updatedAt: '2026-08-01 16:08',
    lastRunAt: '今天 08:00',
  },
  {
    id: 'wf-refund-review',
    name: '退款风险审核',
    description: '结合订单、行为和规则模型判断退款风险并触发复核。',
    category: '风险控制',
    status: 'draft',
    version: 'v0.8.0',
    icon: 'i-lucide:shield-check',
    owner: owners.chen,
    trigger: 'API 调用',
    nodeCount: 9,
    runCount: 128,
    successRate: 91.5,
    averageDuration: '6.2s',
    createdAt: '2026-07-12 11:26',
    updatedAt: '2026-08-04 08:45',
    lastRunAt: '昨天 19:28',
  },
  {
    id: 'wf-contract-extract',
    name: '合同要素抽取',
    description: '从合同附件中提取主体、金额、期限和风险条款。',
    category: '文档处理',
    status: 'published',
    version: 'v1.4.2',
    icon: 'i-lucide:file-scan',
    owner: owners.chen,
    trigger: '文件上传',
    nodeCount: 8,
    runCount: 4721,
    successRate: 97.8,
    averageDuration: '12.3s',
    createdAt: '2026-03-16 15:40',
    updatedAt: '2026-07-30 10:12',
    lastRunAt: '13 分钟前',
  },
  {
    id: 'wf-invoice-check',
    name: '发票验真与归档',
    description: '识别发票、调用验真服务并按规则归档到财务系统。',
    category: '财务自动化',
    status: 'disabled',
    version: 'v1.2.0',
    icon: 'i-lucide:receipt-text',
    owner: owners.qiao,
    trigger: '邮件附件',
    nodeCount: 10,
    runCount: 2357,
    successRate: 94.1,
    averageDuration: '8.7s',
    createdAt: '2026-01-09 13:15',
    updatedAt: '2026-07-26 18:22',
    lastRunAt: '7 月 26 日',
  },
  {
    id: 'wf-meeting-summary',
    name: '会议纪要与行动项',
    description: '转写会议内容，生成结构化纪要并自动分发行动项。',
    category: '协作办公',
    status: 'published',
    version: 'v2.0.4',
    icon: 'i-lucide:notebook-tabs',
    owner: owners.lin,
    trigger: '会议结束',
    nodeCount: 12,
    runCount: 3188,
    successRate: 98.1,
    averageDuration: '22.9s',
    createdAt: '2026-04-28 16:05',
    updatedAt: '2026-07-24 14:37',
    lastRunAt: '31 分钟前',
  },
  {
    id: 'wf-content-review',
    name: '内容合规审核',
    description: '检查敏感信息、品牌规范和内容质量，输出修订建议。',
    category: '内容运营',
    status: 'published',
    version: 'v1.7.5',
    icon: 'i-lucide:scan-text',
    owner: owners.shen,
    trigger: '内容提交',
    nodeCount: 13,
    runCount: 7620,
    successRate: 97.2,
    averageDuration: '5.5s',
    createdAt: '2026-03-11 10:48',
    updatedAt: '2026-07-23 09:52',
    lastRunAt: '4 分钟前',
  },
  {
    id: 'wf-ticket-classify',
    name: '工单分类与升级',
    description: '识别问题类型与紧急程度，自动路由并升级高风险工单。',
    category: '客户服务',
    status: 'draft',
    version: 'v0.5.1',
    icon: 'i-lucide:ticket-check',
    owner: owners.lin,
    trigger: '工单创建',
    nodeCount: 6,
    runCount: 89,
    successRate: 88.8,
    averageDuration: '3.1s',
    createdAt: '2026-07-22 12:20',
    updatedAt: '2026-07-22 15:46',
    lastRunAt: '7 月 22 日',
  },
  {
    id: 'wf-stock-alert',
    name: '库存异常预警',
    description: '监控库存变化并结合销售趋势触发补货或积压预警。',
    category: '供应链',
    status: 'published',
    version: 'v2.3.0',
    icon: 'i-lucide:warehouse',
    owner: owners.qiao,
    trigger: '每 10 分钟',
    nodeCount: 9,
    runCount: 24682,
    successRate: 99.6,
    averageDuration: '1.9s',
    createdAt: '2025-12-08 08:30',
    updatedAt: '2026-07-18 11:05',
    lastRunAt: '1 分钟前',
  },
  {
    id: 'wf-onboarding',
    name: '新员工入职协同',
    description: '串联账号、设备、培训和导师任务，跟踪入职完成度。',
    category: '人力资源',
    status: 'published',
    version: 'v1.5.0',
    icon: 'i-lucide:user-round-plus',
    owner: owners.shen,
    trigger: '入职单创建',
    nodeCount: 15,
    runCount: 946,
    successRate: 98.9,
    averageDuration: '9.4s',
    createdAt: '2026-02-04 17:18',
    updatedAt: '2026-07-15 16:33',
    lastRunAt: '昨天 10:06',
  },
  {
    id: 'wf-data-quality',
    name: '客户数据质量巡检',
    description: '检测重复、缺失与异常客户数据并生成治理任务。',
    category: '数据治理',
    status: 'disabled',
    version: 'v1.0.7',
    icon: 'i-lucide:database-zap',
    owner: owners.qiao,
    trigger: '每日 02:00',
    nodeCount: 8,
    runCount: 186,
    successRate: 93.5,
    averageDuration: '42.8s',
    createdAt: '2026-01-18 09:55',
    updatedAt: '2026-06-30 14:20',
    lastRunAt: '6 月 30 日',
  },
]

function createSteps(status: WorkflowRunStatus): WorkflowRunStep[] {
  const stopped = status === 'failed' || status === 'terminated'
  const active = status === 'running' || status === 'suspended'
  return [
    {
      id: 'step-trigger',
      name: '接收触发事件',
      type: '触发器',
      status: 'success',
      startedAt: '10:24:08.042',
      duration: '42ms',
      detail: '触发参数已通过 Schema 校验。',
    },
    {
      id: 'step-context',
      name: '加载业务上下文',
      type: '数据处理',
      status: 'success',
      startedAt: '10:24:08.084',
      duration: '318ms',
      detail: '已加载客户信息和最近 10 条交互记录。',
    },
    {
      id: 'step-model',
      name: '模型推理',
      type: '大模型',
      status: stopped ? 'failed' : active ? 'running' : 'success',
      startedAt: '10:24:08.402',
      duration: stopped ? '2.8s' : active ? '执行中' : '1.7s',
      detail: stopped
        ? '上游模型服务返回超时，已达到重试上限。'
        : '正在生成结构化结果并执行质量检查。',
    },
    {
      id: 'step-output',
      name: '写入业务结果',
      type: '连接器',
      status: stopped || active ? 'pending' : 'success',
      duration: stopped || active ? '-' : '286ms',
      detail: '将结果写入业务系统并发送通知。',
    },
  ]
}

export const initialWorkflowInstances: WorkflowRunInstance[] = [
  {
    id: 'RUN-20260804-10428',
    traceId: 'tr_9f71c2e84b6a',
    workflowId: 'wf-customer-service',
    workflowName: '智能客服自动化',
    version: 'v2.6.0',
    status: 'running',
    environment: 'production',
    trigger: '消息事件',
    initiator: '客户会话 #C2841',
    currentNode: '模型推理',
    progress: 68,
    startedAt: '2026-08-04 10:24:08',
    duration: '3.2s',
    retries: 0,
    steps: createSteps('running'),
  },
  {
    id: 'RUN-20260804-10427',
    traceId: 'tr_674b820da38f',
    workflowId: 'wf-lead-routing',
    workflowName: '销售线索智能分配',
    version: 'v1.9.3',
    status: 'failed',
    environment: 'production',
    trigger: 'Webhook',
    initiator: '官网表单 #L8920',
    currentNode: '模型推理',
    progress: 52,
    startedAt: '2026-08-04 10:23:42',
    finishedAt: '2026-08-04 10:23:49',
    duration: '7.1s',
    retries: 2,
    steps: createSteps('failed'),
  },
  {
    id: 'RUN-20260804-10426',
    traceId: 'tr_1d396f0cf270',
    workflowId: 'wf-stock-alert',
    workflowName: '库存异常预警',
    version: 'v2.3.0',
    status: 'success',
    environment: 'production',
    trigger: '定时任务',
    initiator: '系统调度器',
    currentNode: '完成',
    progress: 100,
    startedAt: '2026-08-04 10:20:00',
    finishedAt: '2026-08-04 10:20:02',
    duration: '1.8s',
    retries: 0,
    steps: createSteps('success'),
  },
  {
    id: 'RUN-20260804-10425',
    traceId: 'tr_e5a368b9f90d',
    workflowId: 'wf-contract-extract',
    workflowName: '合同要素抽取',
    version: 'v1.4.2',
    status: 'running',
    environment: 'staging',
    trigger: '文件上传',
    initiator: '陈墨',
    currentNode: '模型推理',
    progress: 74,
    startedAt: '2026-08-04 10:19:31',
    duration: '11.4s',
    retries: 0,
    steps: createSteps('running'),
  },
  {
    id: 'RUN-20260804-10424',
    traceId: 'tr_707ca9164b4f',
    workflowId: 'wf-content-review',
    workflowName: '内容合规审核',
    version: 'v1.7.5',
    status: 'suspended',
    environment: 'production',
    trigger: '内容提交',
    initiator: '内容平台 #P1603',
    currentNode: '等待人工复核',
    progress: 81,
    startedAt: '2026-08-04 10:16:20',
    duration: '等待 4m 12s',
    retries: 0,
    steps: createSteps('suspended'),
  },
  {
    id: 'RUN-20260804-10423',
    traceId: 'tr_ad19fc05110b',
    workflowId: 'wf-meeting-summary',
    workflowName: '会议纪要与行动项',
    version: 'v2.0.4',
    status: 'success',
    environment: 'production',
    trigger: '会议结束',
    initiator: '产品周会',
    currentNode: '完成',
    progress: 100,
    startedAt: '2026-08-04 10:12:03',
    finishedAt: '2026-08-04 10:12:26',
    duration: '22.6s',
    retries: 0,
    steps: createSteps('success'),
  },
  {
    id: 'RUN-20260804-10422',
    traceId: 'tr_2c2f49606ced',
    workflowId: 'wf-customer-service',
    workflowName: '智能客服自动化',
    version: 'v2.6.0',
    status: 'success',
    environment: 'production',
    trigger: '消息事件',
    initiator: '客户会话 #C2819',
    currentNode: '完成',
    progress: 100,
    startedAt: '2026-08-04 10:11:38',
    finishedAt: '2026-08-04 10:11:41',
    duration: '2.5s',
    retries: 0,
    steps: createSteps('success'),
  },
  {
    id: 'RUN-20260804-10421',
    traceId: 'tr_97ac420891bb',
    workflowId: 'wf-weekly-report',
    workflowName: '运营周报生成',
    version: 'v3.1.1',
    status: 'terminated',
    environment: 'staging',
    trigger: '手动运行',
    initiator: '乔安',
    currentNode: '已终止',
    progress: 38,
    startedAt: '2026-08-04 10:08:12',
    finishedAt: '2026-08-04 10:08:20',
    duration: '8.4s',
    retries: 0,
    steps: createSteps('terminated'),
  },
]

export const initialWorkflowAlerts: WorkflowAlert[] = [
  {
    id: 'alert-timeout',
    severity: 'critical',
    title: '模型节点连续超时',
    message: '5 分钟内发生 3 次超时，已触发降级策略。',
    workflowName: '销售线索智能分配',
    instanceId: 'RUN-20260804-10427',
    createdAt: '1 分钟前',
    acknowledged: false,
  },
  {
    id: 'alert-suspended',
    severity: 'warning',
    title: '人工复核等待时间过长',
    message: '实例已等待超过 4 分钟，请检查当前审批人。',
    workflowName: '内容合规审核',
    instanceId: 'RUN-20260804-10424',
    createdAt: '4 分钟前',
    acknowledged: false,
  },
  {
    id: 'alert-rate',
    severity: 'warning',
    title: '成功率低于告警阈值',
    message: '最近 15 分钟成功率为 94.6%，阈值为 96%。',
    workflowName: '销售线索智能分配',
    instanceId: 'RUN-20260804-10427',
    createdAt: '12 分钟前',
    acknowledged: false,
  },
  {
    id: 'alert-recovered',
    severity: 'info',
    title: '连接器服务已恢复',
    message: 'CRM 连接器响应时间已恢复到正常范围。',
    workflowName: '智能客服自动化',
    instanceId: 'RUN-20260804-10422',
    createdAt: '28 分钟前',
    acknowledged: true,
  },
]

export const workflowThroughput: WorkflowThroughputPoint[] = [
  { label: '09:55', success: 48, failed: 2 },
  { label: '10:00', success: 62, failed: 3 },
  { label: '10:05', success: 55, failed: 1 },
  { label: '10:10', success: 74, failed: 4 },
  { label: '10:15', success: 68, failed: 2 },
  { label: '10:20', success: 86, failed: 5 },
  { label: '10:25', success: 78, failed: 2 },
]

export const workflowLatencyRanks: WorkflowLatencyRank[] = [
  {
    node: '模型推理',
    workflowName: '运营周报生成',
    duration: 12.8,
    unit: 's',
  },
  {
    node: '合同结构解析',
    workflowName: '合同要素抽取',
    duration: 8.4,
    unit: 's',
  },
  {
    node: '知识库召回',
    workflowName: '智能客服自动化',
    duration: 860,
    unit: 'ms',
  },
  {
    node: 'CRM 写入',
    workflowName: '销售线索智能分配',
    duration: 540,
    unit: 'ms',
  },
]

export function findWorkflowDefinition(id?: string) {
  return initialWorkflowDefinitions.find((item) => item.id === id)
}
