import type {
  ChartAiMessage,
  ChartAiSuggestion,
  ChartDataSource,
  ChartScreenConfig,
  ChartWidget,
} from './types'
export {
  chartControlPalette as chartPalette,
  favoriteChartPalette,
} from './components/controls/registry'

export const aiSuggestions: ChartAiSuggestion[] = [
  {
    id: 'sales',
    title: '销售经营大屏',
    prompt:
      '生成一个销售经营数据大屏，包含 GMV、转化率、区域销售排行、渠道占比和近 7 天趋势。',
    icon: 'i-lucide:badge-dollar-sign',
  },
  {
    id: 'growth',
    title: '增长转化看板',
    prompt:
      '帮我设计增长转化大屏，关注线索、商机、试用、成交漏斗和各渠道贡献。',
    icon: 'i-lucide:trending-up',
  },
  {
    id: 'ops',
    title: '系统监控中心',
    prompt:
      '生成一个系统监控大屏，展示在线服务、CPU、告警、接口耗时和资源使用趋势。',
    icon: 'i-lucide:activity',
  },
]

export const defaultScreenConfig: ChartScreenConfig = {
  title: 'AI 数据大屏设计器',
  subtitle: '自然语言生成图表布局，并绑定可预览的数据源',
  theme: 'midnight',
  canvasBackground: '#07111f',
  previewMode: 'dark',
  width: 1920,
  height: 1080,
  autoRefresh: true,
}

export const chartDataSources: ChartDataSource[] = [
  {
    id: 'sales',
    name: '销售订单数据',
    kind: 'sample',
    status: 'online',
    description: '订单、区域、渠道、GMV 和毛利率样例数据',
    endpoint: '/api/bi/sales/orders',
    refreshInterval: 60,
    updatedAt: '2026-06-12 09:30',
    fields: [
      { key: 'date', label: '日期', type: 'date' },
      { key: 'region', label: '区域', type: 'string' },
      { key: 'channel', label: '渠道', type: 'string' },
      { key: 'gmv', label: 'GMV', type: 'currency' },
      { key: 'orders', label: '订单数', type: 'number' },
      { key: 'conversion', label: '转化率', type: 'percent' },
      { key: 'grossMargin', label: '毛利率', type: 'percent' },
    ],
    records: [
      {
        date: '06-06',
        region: '华东',
        channel: '直营',
        gmv: 286000,
        orders: 326,
        conversion: 0.132,
        grossMargin: 0.236,
      },
      {
        date: '06-07',
        region: '华北',
        channel: '电商',
        gmv: 238000,
        orders: 281,
        conversion: 0.118,
        grossMargin: 0.214,
      },
      {
        date: '06-08',
        region: '华南',
        channel: '分销',
        gmv: 312000,
        orders: 356,
        conversion: 0.146,
        grossMargin: 0.251,
      },
      {
        date: '06-09',
        region: '西南',
        channel: '伙伴',
        gmv: 176000,
        orders: 209,
        conversion: 0.103,
        grossMargin: 0.186,
      },
      {
        date: '06-10',
        region: '华中',
        channel: '直营',
        gmv: 351000,
        orders: 392,
        conversion: 0.154,
        grossMargin: 0.267,
      },
      {
        date: '06-11',
        region: '东北',
        channel: '电商',
        gmv: 194000,
        orders: 236,
        conversion: 0.109,
        grossMargin: 0.192,
      },
      {
        date: '06-12',
        region: '海外',
        channel: '伙伴',
        gmv: 428000,
        orders: 418,
        conversion: 0.169,
        grossMargin: 0.284,
      },
    ],
  },
  {
    id: 'growth',
    name: '增长转化漏斗',
    kind: 'rest',
    status: 'online',
    description: '线索、商机、试用和成交阶段数据',
    endpoint: '/api/bi/growth/funnel',
    refreshInterval: 300,
    updatedAt: '2026-06-12 09:20',
    fields: [
      { key: 'stage', label: '阶段', type: 'string' },
      { key: 'channel', label: '渠道', type: 'string' },
      { key: 'count', label: '数量', type: 'number' },
      { key: 'cost', label: '成本', type: 'currency' },
      { key: 'rate', label: '转化率', type: 'percent' },
    ],
    records: [
      { stage: '曝光', channel: '内容', count: 128000, cost: 32000, rate: 1 },
      { stage: '访问', channel: '内容', count: 48600, cost: 32000, rate: 0.38 },
      {
        stage: '留资',
        channel: '广告',
        count: 13200,
        cost: 84000,
        rate: 0.272,
      },
      { stage: '试用', channel: '活动', count: 4260, cost: 45000, rate: 0.323 },
      { stage: '成交', channel: '伙伴', count: 1160, cost: 38000, rate: 0.272 },
    ],
  },
  {
    id: 'ops',
    name: '系统监控指标',
    kind: 'sql',
    status: 'draft',
    description: '服务健康度、接口耗时和资源趋势',
    endpoint: 'mysql://bi_monitor/service_metrics',
    refreshInterval: 30,
    updatedAt: '2026-06-12 09:10',
    fields: [
      { key: 'time', label: '时间', type: 'date' },
      { key: 'service', label: '服务', type: 'string' },
      { key: 'cpu', label: 'CPU', type: 'percent' },
      { key: 'latency', label: '耗时', type: 'number' },
      { key: 'alerts', label: '告警数', type: 'number' },
    ],
    records: [
      { time: '09:00', service: 'gateway', cpu: 0.42, latency: 86, alerts: 1 },
      { time: '09:05', service: 'auth', cpu: 0.36, latency: 64, alerts: 0 },
      { time: '09:10', service: 'order', cpu: 0.58, latency: 138, alerts: 2 },
      { time: '09:15', service: 'crm', cpu: 0.49, latency: 112, alerts: 0 },
      { time: '09:20', service: 'report', cpu: 0.63, latency: 164, alerts: 3 },
    ],
  },
]

export const defaultWidgets: ChartWidget[] = [
  {
    id: 'w-gmv',
    title: '今日 GMV',
    subtitle: '销售订单数据',
    kind: 'kpi',
    sourceId: 'sales',
    dimension: 'date',
    measure: 'gmv',
    colSpan: 3,
    rowSpan: 1,
    accent: '#3b82f6',
    insight: 'GMV 环比保持增长，海外和华中贡献明显。',
    formatter: 'currency',
  },
  {
    id: 'w-conversion',
    title: '平均转化率',
    subtitle: '近 7 日',
    kind: 'kpi',
    sourceId: 'sales',
    dimension: 'date',
    measure: 'conversion',
    colSpan: 3,
    rowSpan: 1,
    accent: '#14b8a6',
    insight: '转化率稳定在 13% 左右，可继续提升分销渠道承接。',
    formatter: 'percent',
  },
  {
    id: 'w-trend',
    title: 'GMV 趋势',
    subtitle: '按日期聚合',
    kind: 'chart',
    chartType: 'area',
    sourceId: 'sales',
    dimension: 'date',
    measure: 'gmv',
    colSpan: 6,
    rowSpan: 2,
    accent: '#3b82f6',
    insight: '最近峰值出现在 06-12，建议标记活动来源。',
    formatter: 'currency',
  },
  {
    id: 'w-region',
    title: '区域销售排行',
    subtitle: '按 GMV 排序',
    kind: 'chart',
    chartType: 'bar',
    sourceId: 'sales',
    dimension: 'region',
    measure: 'gmv',
    colSpan: 6,
    rowSpan: 2,
    accent: '#f59e0b',
    insight: '海外、华中、华南是当前主要贡献区域。',
    formatter: 'currency',
  },
  {
    id: 'w-channel',
    title: '渠道结构',
    subtitle: '订单量占比',
    kind: 'chart',
    chartType: 'pie',
    sourceId: 'sales',
    dimension: 'channel',
    measure: 'orders',
    colSpan: 4,
    rowSpan: 2,
    accent: '#8b5cf6',
    insight: '直营和电商订单占比较高，伙伴渠道客单价更高。',
    formatter: 'number',
  },
  {
    id: 'w-funnel',
    title: '增长转化漏斗',
    subtitle: '线索到成交',
    kind: 'chart',
    chartType: 'funnel',
    sourceId: 'growth',
    dimension: 'stage',
    measure: 'count',
    colSpan: 4,
    rowSpan: 2,
    accent: '#06b6d4',
    insight: '留资到试用阶段损耗最大，建议优化试用引导。',
    formatter: 'number',
  },
  {
    id: 'w-note',
    title: 'AI 经营洞察',
    subtitle: '自动生成',
    kind: 'note',
    sourceId: 'sales',
    dimension: 'region',
    measure: 'gmv',
    colSpan: 4,
    rowSpan: 2,
    accent: '#22c55e',
    insight:
      '高 GMV 区域集中在海外和华中。下一步建议拆分活动、渠道和客单价，定位增长来源并设置异常阈值。',
  },
]

export const initialAiMessages: ChartAiMessage[] = [
  {
    id: 'm-welcome',
    role: 'assistant',
    content:
      '描述你要分析的业务目标，我会自动选择数据源、生成大屏布局和图表配置。你也可以继续手动调整每个组件。',
    createdAt: '09:30',
  },
]
