import type { KnowledgeBaseItem, KnowledgeBasePageConfig } from './types'

export const knowledgeBasePageConfig: KnowledgeBasePageConfig = {
  kind: 'knowledge-base',
  title: '知识库',
  subtitle: '集中维护文档、FAQ、制度和业务知识，为 Agent 提供可信上下文。',
  icon: 'i-lucide:library-big',
  createText: '新建知识库',
  searchPlaceholder: '搜索知识库名称、描述、标签或创建人',
  emptyText: '没有符合条件的知识库',
  totalText: '知识库',
  activeText: '已启用',
  draftText: '待完善',
  statusLabels: {
    online: '已启用',
    draft: '待完善',
    offline: '已停用',
  },
}

export const knowledgeBaseResources: KnowledgeBaseItem[] = [
  {
    id: 'kb-product-handbook',
    kind: 'knowledge-base',
    name: '产品能力手册',
    description:
      '沉淀后台管理、低代码、报表、工作流等模块的功能说明和配置规则。',
    tags: ['产品文档', '低代码', '工作流'],
    creator: { name: '叶舟', role: '产品经理' },
    createdAt: '2026-07-10 09:12',
    updatedAt: '2026-08-03 20:24',
    status: 'online',
    icon: 'i-lucide:notebook-tabs',
    iconBackground: '#E0F2FE',
    metrics: [
      { label: '文档数', value: '286', tone: 'primary' },
      { label: '命中率', value: '91%', tone: 'success' },
      { label: '更新频率', value: '每日' },
    ],
  },
  {
    id: 'kb-finance-policy',
    kind: 'knowledge-base',
    name: '财务制度知识库',
    description:
      '包含报销、预算、发票、对账和月结制度，用于财务问答和审批校验。',
    tags: ['财务制度', '审批', '风控'],
    creator: { name: '林佳', role: '财务 BP' },
    createdAt: '2026-07-14 16:38',
    updatedAt: '2026-08-04 08:50',
    status: 'online',
    icon: 'i-lucide:landmark',
    iconBackground: '#DCFCE7',
    metrics: [
      { label: '条目数', value: '1.8k', tone: 'primary' },
      { label: '引用次数', value: '9.6k' },
      { label: '可信分', value: '96', tone: 'success' },
    ],
  },
  {
    id: 'kb-customer-service',
    kind: 'knowledge-base',
    name: '客服 FAQ 知识库',
    description:
      '聚合售前咨询、售后处理、价格政策和常见异常，支持客服 Agent 检索。',
    tags: ['客服', 'FAQ', '售后'],
    creator: { name: '王若溪', role: '客服经理' },
    createdAt: '2026-07-19 11:06',
    updatedAt: '2026-08-04 10:04',
    status: 'online',
    icon: 'i-lucide:message-circle-question',
    iconBackground: '#FCE7F3',
    metrics: [
      { label: '问答对', value: '3.2k', tone: 'primary' },
      { label: '采纳率', value: '82%', tone: 'success' },
      { label: '低置信', value: '41', tone: 'warning' },
    ],
  },
  {
    id: 'kb-warehouse-sop',
    kind: 'knowledge-base',
    name: '仓储 SOP 知识库',
    description:
      '覆盖入库、上架、拣货、复核、出库和盘点流程，支持一线作业问答。',
    tags: ['WMS', 'SOP', '作业规范'],
    creator: { name: '赵敏', role: '仓储主管' },
    createdAt: '2026-07-22 13:45',
    updatedAt: '2026-08-02 19:12',
    status: 'draft',
    icon: 'i-lucide:warehouse',
    iconBackground: '#FEF3C7',
    metrics: [
      { label: '流程文档', value: '74' },
      { label: '待审核', value: '12', tone: 'warning' },
      { label: '版本', value: 'v0.9' },
    ],
  },
  {
    id: 'kb-contract-clause',
    kind: 'knowledge-base',
    name: '合同条款知识库',
    description:
      '沉淀常用商务条款、风险条款和法务审查意见，为合同审阅提供依据。',
    tags: ['合同', '法务', '条款'],
    creator: { name: '顾言', role: '法务顾问' },
    createdAt: '2026-07-25 10:18',
    updatedAt: '2026-08-01 15:27',
    status: 'online',
    icon: 'i-lucide:scroll-text',
    iconBackground: '#EDE9FE',
    metrics: [
      { label: '条款库', value: '612', tone: 'primary' },
      { label: '风险规则', value: '84', tone: 'warning' },
      { label: '引用率', value: '78%' },
    ],
  },
  {
    id: 'kb-implementation-playbook',
    kind: 'knowledge-base',
    name: '实施交付知识库',
    description:
      '记录需求调研、蓝图设计、上线切换和培训材料，用于项目交付复盘。',
    tags: ['实施', '交付', '项目管理'],
    creator: { name: '沈牧', role: '实施顾问' },
    createdAt: '2026-07-28 17:08',
    updatedAt: '2026-08-03 10:36',
    status: 'offline',
    icon: 'i-lucide:book-open-check',
    iconBackground: '#CFFAFE',
    metrics: [
      { label: '项目案例', value: '38' },
      { label: '复用率', value: '64%' },
      { label: '状态', value: '整理中', tone: 'warning' },
    ],
  },
  {
    id: 'kb-bi-metrics',
    kind: 'knowledge-base',
    name: '经营指标口径库',
    description:
      '统一销售、库存、财务和运营指标口径，避免报表和 Agent 回答不一致。',
    tags: ['BI', '指标口径', '数据治理'],
    creator: { name: '许宁', role: '数据产品' },
    createdAt: '2026-08-01 09:44',
    updatedAt: '2026-08-04 09:22',
    status: 'online',
    icon: 'i-lucide:database-zap',
    iconBackground: '#E0E7FF',
    metrics: [
      { label: '指标数', value: '156', tone: 'primary' },
      { label: '负责人', value: '12' },
      { label: '一致率', value: '94%', tone: 'success' },
    ],
  },
]
