import dayjs from 'dayjs'
import type { TaskCenterItem } from './types'

export const initialTaskCenterItems: TaskCenterItem[] = [
  {
    id: 'task-1001',
    title: '导出本月订单明细',
    description: '生成运营复盘需要的订单、退款、渠道来源明细。',
    type: 'export',
    status: 'running',
    progress: 68,
    owner: '运营组',
    source: '订单中心 / 2026-06',
    target: '任务中心 / exports/orders-june.xlsx',
    size: '128 MB',
    speed: '4.8 MB/s',
    createdAt: dayjs().subtract(16, 'minute').format('YYYY-MM-DD HH:mm:ss'),
    updatedAt: dayjs().subtract(1, 'minute').format('YYYY-MM-DD HH:mm:ss'),
    logs: [
      '任务已创建，等待调度资源。',
      '已读取订单索引，开始分片导出。',
      '正在写入 Excel 工作簿。',
    ],
  },
  {
    id: 'task-1002',
    title: '同步客户标签数据',
    description: '将 CRM 标签同步到分析库，用于人群筛选和看板统计。',
    type: 'sync',
    status: 'waiting',
    progress: 12,
    owner: '系统服务',
    source: 'CRM 客户标签',
    target: 'Analysis Warehouse',
    size: '46,280 条',
    speed: '等待资源',
    createdAt: dayjs().subtract(42, 'minute').format('YYYY-MM-DD HH:mm:ss'),
    updatedAt: dayjs().subtract(7, 'minute').format('YYYY-MM-DD HH:mm:ss'),
    logs: ['任务已入队。', '等待上一个同步任务释放连接。'],
  },
  {
    id: 'task-1003',
    title: '下载活动素材包',
    description: '下载端午活动 Banner、落地页图片和投放素材。',
    type: 'download',
    status: 'success',
    progress: 100,
    owner: '运营组',
    source: '素材库 / campaign/dragon-boat',
    target: '本地下载 / campaign-assets.zip',
    size: '386 MB',
    speed: '已完成',
    createdAt: dayjs().subtract(3, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    updatedAt: dayjs().subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    logs: ['任务已创建。', '下载完成，文件校验通过。'],
  },
  {
    id: 'task-1004',
    title: '导入供应商报价单',
    description: '批量导入供应商最新价格，失败项需要人工复核。',
    type: 'import',
    status: 'failed',
    progress: 41,
    owner: '财务组',
    source: 'supplier-price-202606.xlsx',
    target: '供应链系统 / 报价库',
    size: '8,640 行',
    speed: '已中断',
    createdAt: dayjs().subtract(1, 'day').format('YYYY-MM-DD HH:mm:ss'),
    updatedAt: dayjs().subtract(23, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    logs: [
      '文件解析完成。',
      '发现 34 条 SKU 缺失供应商编码。',
      '任务失败，请修正数据后重试。',
    ],
  },
  {
    id: 'task-1005',
    title: '系统配置备份',
    description: '备份菜单、角色、字典和项目配置，保留 30 天。',
    type: 'backup',
    status: 'paused',
    progress: 54,
    owner: '系统服务',
    source: 'Admin Config',
    target: 'Backup Storage / daily',
    size: '92 MB',
    speed: '已暂停',
    createdAt: dayjs().subtract(2, 'day').format('YYYY-MM-DD HH:mm:ss'),
    updatedAt: dayjs().subtract(1, 'day').format('YYYY-MM-DD HH:mm:ss'),
    logs: ['任务已创建。', '用户暂停了任务。'],
  },
]
