import type { ChartWidget } from '../types'
import { createDesignerId } from './ids'

export function createOpsWidgets(): ChartWidget[] {
  return [
    {
      accent: '#22c55e',
      colSpan: 3,
      dimension: 'time',
      formatter: 'percent',
      id: createDesignerId('widget'),
      insight: 'CPU 当前处于可控区间，report 服务负载略高。',
      kind: 'kpi',
      measure: 'cpu',
      rowSpan: 1,
      sourceId: 'ops',
      subtitle: '系统监控指标',
      title: '平均 CPU',
    },
    {
      accent: '#ef4444',
      colSpan: 3,
      dimension: 'time',
      formatter: 'number',
      id: createDesignerId('widget'),
      insight: '告警集中在 order 和 report 服务，应设置追踪任务。',
      kind: 'kpi',
      measure: 'alerts',
      rowSpan: 1,
      sourceId: 'ops',
      subtitle: '近 20 分钟',
      title: '告警总数',
    },
    {
      accent: '#38bdf8',
      chartType: 'heatmap',
      colSpan: 6,
      dimension: 'time',
      formatter: 'number',
      id: createDesignerId('widget'),
      insight: '耗时在 report 服务出现抬升，需要结合慢查询排查。',
      kind: 'chart',
      measure: 'latency',
      rowSpan: 2,
      sourceId: 'ops',
      subtitle: 'P95 Latency',
      title: '接口耗时趋势',
    },
    {
      accent: '#a3e635',
      chartType: 'radar',
      colSpan: 6,
      dimension: 'service',
      formatter: 'percent',
      id: createDesignerId('widget'),
      insight: 'report、order 服务资源占用较高。',
      kind: 'chart',
      measure: 'cpu',
      rowSpan: 2,
      sourceId: 'ops',
      subtitle: '按服务聚合',
      title: '服务健康雷达',
    },
    {
      accent: '#f97316',
      colSpan: 6,
      dimension: 'service',
      id: createDesignerId('widget'),
      insight:
        '建议为 report 服务增加慢查询面板，并把接口耗时、错误率和实例数放在同屏关联分析。',
      kind: 'note',
      measure: 'latency',
      rowSpan: 2,
      sourceId: 'ops',
      subtitle: '自动生成',
      title: 'AI 运维建议',
    },
  ]
}

export function createGrowthWidgets(): ChartWidget[] {
  return [
    {
      accent: '#14b8a6',
      colSpan: 3,
      dimension: 'stage',
      formatter: 'number',
      id: createDesignerId('widget'),
      insight: '成交阶段数量 1160，整体转化仍有优化空间。',
      kind: 'kpi',
      measure: 'count',
      rowSpan: 1,
      sourceId: 'growth',
      subtitle: '增长漏斗',
      title: '成交数',
    },
    {
      accent: '#06b6d4',
      chartType: 'funnel',
      colSpan: 7,
      dimension: 'stage',
      formatter: 'number',
      id: createDesignerId('widget'),
      insight: '留资到试用阶段损耗最大，建议优化首触达体验。',
      kind: 'chart',
      measure: 'count',
      rowSpan: 2,
      sourceId: 'growth',
      subtitle: '曝光到成交',
      title: '转化漏斗',
    },
    {
      accent: '#f59e0b',
      chartType: 'scatter',
      colSpan: 5,
      dimension: 'channel',
      formatter: 'currency',
      id: createDesignerId('widget'),
      insight: '广告渠道成本最高，需要结合成交贡献评估 ROI。',
      kind: 'chart',
      measure: 'cost',
      rowSpan: 2,
      sourceId: 'growth',
      subtitle: '按渠道',
      title: '渠道成本分布',
    },
    {
      accent: '#8b5cf6',
      colSpan: 5,
      dimension: 'stage',
      id: createDesignerId('widget'),
      insight:
        '把漏斗拆成渠道和阶段两个视角，优先分析留资到试用的承接内容、跟进时效和人群差异。',
      kind: 'note',
      measure: 'rate',
      rowSpan: 2,
      sourceId: 'growth',
      subtitle: '自动生成',
      title: 'AI 增长建议',
    },
  ]
}
