export { default as SearchModal } from './searchModal/index.vue'
export { default as Setting } from '../preferences/index.vue'
export { default as NoticeCenter } from './noticeCenter/index.vue'
export { default as DownloadCenter } from './downloadCenter/index.vue'
export { default as NoteBookModal } from './noteBookModal/index.vue'
export { default as ChatModal } from './chatModal/index.vue'
export { default as ChangePassword } from './changePassword/index.vue'
export { default as LockScreenModal } from './lockScreen/index.vue'
