import type { IMenu } from '#/config'

export const menus: IMenu[] = [
  {
    id: 1,
    title: 'Dashboard',
    type: 0,
    path: '/',
    rootId: 0,
    parentId: 0,
    level: '1',
    icon: 'i-lucide:layout-dashboard',
    iconBgColor: '#1677ff',
    iconShape: 'round',
    children: [
      {
        id: 11,
        title: '分析页',
        path: '/dashboard/analysis',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-11',
        icon: 'i-lucide:chart-no-axes-combined',
        home: true,
        keepAlive: true,
      },
      {
        id: 12,
        title: '工作台',
        path: '/dashboard/workbench',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-12',
        icon: 'i-lucide:briefcase-business',
        keepAlive: true,
      },
      {
        id: 13,
        title: '监控页',
        path: '/dashboard/monitor',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-13',
        icon: 'i-lucide:activity',
        keepAlive: true,
      },
      {
        id: 14,
        title: '我的任务',
        path: '/dashboard/task',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-14',
        icon: 'i-lucide:list-checks',
      },
      {
        id: 15,
        title: '文件管理',
        path: '/dashboard/fileManger',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-15',
        icon: 'i-lucide:folder-open',
      },
      {
        id: 16,
        title: '工单',
        type: 0,
        rootId: 1,
        parentId: 1,
        level: '1-16',
        icon: 'i-lucide:ticket-check',
        children: [
          {
            id: 161,
            title: '工单中心',
            path: '/dashboard/ticket/center',
            type: 1,
            rootId: 1,
            parentId: 16,
            level: '1-16-161',
            icon: 'i-lucide:ticket-check',
          },
          {
            id: 162,
            title: '工单处理',
            path: '/dashboard/ticket/management',
            type: 1,
            rootId: 1,
            parentId: 16,
            level: '1-16-162',
            icon: 'i-lucide:headset',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: '客户',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '2',
    icon: 'i-lucide:users',
    children: [
      {
        id: 21,
        title: '客户管理',
        type: 0,
        rootId: 2,
        parentId: 2,
        level: '2-21',
        icon: 'i-lucide:user-round-cog',
        children: [
          {
            id: 211,
            title: '客户管理',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-211',
            icon: 'i-lucide:users',
            path: '/cust/customer/manage',
          },
          {
            id: 212,
            title: '客户属性管理',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-212',
            icon: 'i-lucide:user-cog',
            path: '/customer/customer/customerProp',
            componentPath: '/cust/customer/customerManage',
          },
          {
            id: 217,
            title: '标签管理',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-217',
            icon: 'i-lucide:tags',
            path: '/cust/customer/label',
          },
          {
            id: 213,
            title: '流失客户',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-213',
            icon: 'i-lucide:user-x',
            path: '/customer/customer/lostCustomer',
            componentPath: '/cust/customer/lostCustomer',
          },
          {
            id: 214,
            title: '删人提醒',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-214',
            icon: 'i-lucide:user-minus',
            path: '/customer/customer/deleteReminder',
            componentPath: '/cust/customer/deleteAlert',
          },
          {
            id: 215,
            title: '在职继承',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-215',
            icon: 'i-lucide:user-round-check',
            path: '/customer/customer/workInherit',
            componentPath: '/cust/customer/activeInherit',
          },
          {
            id: 216,
            title: '离职继承',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-216',
            icon: 'i-lucide:user-round-x',
            path: '/customer/customer/resignInherit',
            componentPath: '/cust/customer/exInherit',
          },
          {
            id: 218,
            title: '黑名单',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-218',
            icon: 'i-lucide:ban',
            path: '/customer/customer/blackList',
            disabled: true,
          },
        ],
      },
      {
        id: 22,
        title: '客户群管理',
        type: 0,
        rootId: 2,
        parentId: 2,
        level: '2-22',
        icon: 'i-lucide:users-round',
        children: [
          {
            id: 221,
            title: '客户群管理',
            type: 1,
            rootId: 2,
            parentId: 22,
            level: '2-22-221',
            icon: 'i-lucide:users-round',
            path: '/customer/customerGroup/customerGroupManage',
            disabled: true,
          },
          {
            id: 222,
            title: '客户群标签',
            type: 1,
            rootId: 2,
            parentId: 22,
            level: '2-22-222',
            icon: 'i-lucide:tags',
            path: '/customer/customerGroup/customerGroupLabel',
            disabled: true,
          },
        ],
      },
      {
        id: 23,
        title: '客户属性',
        type: 0,
        rootId: 2,
        parentId: 2,
        level: '2-23',
        icon: 'i-lucide:sliders-horizontal',
        children: [
          {
            id: 231,
            title: '客户阶段管理',
            type: 1,
            rootId: 2,
            parentId: 23,
            level: '2-23-231',
            icon: 'i-lucide:kanban',
            path: '/customer/customerProp/customerStage',
            disabled: true,
          },
          {
            id: 232,
            title: '自动打标签',
            type: 1,
            rootId: 2,
            parentId: 23,
            level: '2-23-232',
            icon: 'i-lucide:tag',
            path: '/customer/customerProp/autoMakeLabel',
            disabled: true,
          },
        ],
      },
    ],
  },

  {
    id: 3,
    title: '组件',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '3',
    icon: 'i-lucide:blocks',
    children: [
      {
        id: 31,
        title: '基础能力',
        type: 0,
        rootId: 3,
        parentId: 3,
        level: '3-31',
        icon: 'i-lucide:blocks',
        children: [
          {
            id: 311,
            title: 'Icon',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-311',
            icon: 'i-lucide:shapes',
            path: '/components/icon',
          },
          {
            id: 312,
            title: 'Loading',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-312',
            icon: 'i-lucide:loader-circle',
            path: '/components/loading',
          },
          {
            id: 313,
            title: 'NumberTicker',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-313',
            icon: 'i-lucide:chart-no-axes-column-increasing',
            path: '/components/number-ticker',
          },
          {
            id: 314,
            title: 'WView',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-314',
            icon: 'i-lucide:panel-top',
            path: '/components/view',
          },
          {
            id: 315,
            title: 'Scrollbar',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-315',
            icon: 'i-lucide:gallery-vertical-end',
            path: '/components/scrollbar',
          },
          {
            id: 316,
            title: 'Container',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-316',
            icon: 'i-lucide:panels-top-left',
            path: '/components/container',
          },
        ],
      },
      {
        id: 32,
        title: '输入与选择',
        type: 0,
        rootId: 3,
        parentId: 3,
        level: '3-32',
        icon: 'i-lucide:mouse-pointer-click',
        children: [
          {
            id: 321,
            title: 'IconSelector',
            type: 1,
            rootId: 3,
            parentId: 32,
            level: '3-32-321',
            icon: 'i-lucide:grid-2x2',
            path: '/components/icon-selector',
          },
          {
            id: 322,
            title: 'IconPicker',
            type: 1,
            rootId: 3,
            parentId: 32,
            level: '3-32-322',
            icon: 'i-lucide:mouse-pointer-click',
            path: '/components/icon-picker',
          },
          {
            id: 323,
            title: 'DatePicker',
            type: 1,
            rootId: 3,
            parentId: 32,
            level: '3-32-323',
            icon: 'i-lucide:calendar-days',
            path: '/components/date-picker',
          },
        ],
      },
      {
        id: 33,
        title: '数据展示',
        type: 0,
        rootId: 3,
        parentId: 3,
        level: '3-33',
        icon: 'i-lucide:braces',
        children: [
          {
            id: 331,
            title: 'CodeEditor',
            type: 1,
            rootId: 3,
            parentId: 33,
            level: '3-33-331',
            icon: 'i-lucide:braces',
            path: '/components/code-editor',
          },
          {
            id: 332,
            title: 'JsonView',
            type: 1,
            rootId: 3,
            parentId: 33,
            level: '3-33-332',
            icon: 'i-lucide:file-json-2',
            path: '/components/json-view',
          },
          {
            id: 333,
            title: 'Exception',
            type: 1,
            rootId: 3,
            parentId: 33,
            level: '3-33-333',
            icon: 'i-lucide:circle-alert',
            path: '/components/exception',
          },
          {
            id: 334,
            title: 'FilePreview',
            type: 1,
            rootId: 3,
            parentId: 33,
            level: '3-33-334',
            icon: 'i-lucide:file-search',
            path: '/components/file-preview',
          },
        ],
      },
      {
        id: 34,
        title: '交互组件',
        type: 0,
        rootId: 3,
        parentId: 3,
        level: '3-34',
        icon: 'i-lucide:hand',
        children: [
          {
            id: 342,
            title: 'Draggable',
            type: 1,
            rootId: 3,
            parentId: 34,
            level: '3-34-342',
            icon: 'i-lucide:grip-vertical',
            path: '/components/draggable',
          },
          {
            id: 343,
            title: 'Modal',
            type: 1,
            rootId: 3,
            parentId: 34,
            level: '3-34-343',
            icon: 'i-lucide:panels-top-left',
            path: '/components/modal',
          },
        ],
      },
      {
        id: 35,
        title: '重型组件',
        type: 0,
        rootId: 3,
        parentId: 3,
        level: '3-35',
        icon: 'i-lucide:boxes',
        children: [
          {
            id: 351,
            title: 'Editor',
            type: 1,
            rootId: 3,
            parentId: 35,
            level: '3-35-351',
            icon: 'i-lucide:notebook-pen',
            path: '/components/editor',
            keepAlive: false,
          },
          {
            id: 352,
            title: 'Cropper',
            type: 1,
            rootId: 3,
            parentId: 35,
            level: '3-35-352',
            icon: 'i-lucide:crop',
            path: '/components/cropper',
            keepAlive: false,
          },
          {
            id: 353,
            title: 'Gantt',
            type: 1,
            rootId: 3,
            parentId: 35,
            level: '3-35-353',
            icon: 'i-lucide:gantt-chart',
            path: '/components/gantt',
            keepAlive: false,
          },
          {
            id: 354,
            title: 'ErrorBoundary',
            type: 1,
            rootId: 3,
            parentId: 35,
            level: '3-35-354',
            icon: 'i-lucide:shield-alert',
            path: '/components/error-boundary',
          },
        ],
      },
      {
        id: 399,
        title: '组件示例',
        type: 2,
        rootId: 3,
        parentId: 3,
        level: '3-399',
        path: '/components/demo',
        componentPath: '/components/icon-selector',
        keepAlive: false,
      },
    ],
  },

  {
    id: 6,
    title: '文章管理',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '6',
    icon: 'i-lucide:newspaper',
    children: [
      {
        id: 61,
        title: '文章列表',
        type: 1,
        rootId: 6,
        parentId: 6,
        level: '6-61',
        icon: 'i-lucide:files',
        path: '/article/list',
      },
      {
        id: 611,
        title: '文章编辑',
        type: 2,
        rootId: 6,
        parentId: 61,
        level: '6-61-611',
        icon: 'i-lucide:file-pen-line',
        path: '/article/editor',
        keepAlive: false,
      },
    ],
  },

  {
    id: 7,
    title: '系统',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '7',
    icon: 'i-lucide:cog',
    children: [
      {
        id: 71,
        title: '用户管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-71',
        icon: 'i-lucide:users',
        path: '/sys/user',
      },
      {
        id: 72,
        title: '个人中心',
        type: 2,
        rootId: 7,
        parentId: 7,
        level: '7-72',
        icon: 'i-lucide:id-card',
        path: '/sys/userProfile',
      },
      {
        id: 73,
        title: '角色管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-73',
        icon: 'i-lucide:shield-check',
        path: '/sys/role',
      },
      {
        id: 74,
        title: '部门管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-74',
        icon: 'i-lucide:building-2',
        path: '/sys/dept',
      },
      {
        id: 75,
        title: '菜单管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-75',
        icon: 'i-lucide:menu',
        path: '/sys/menu',
      },
      {
        id: 76,
        title: '通知公告',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-76',
        icon: 'i-lucide:bell',
        path: '/sys/notice',
      },
      {
        id: 77,
        title: '文件管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-77',
        icon: 'i-lucide:file',
        path: '/sys/file',
      },
      {
        id: 78,
        title: '字典管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-78',
        icon: 'i-lucide:book-type',
        path: '/sys/dict',
      },
      {
        id: 79,
        title: '系统配置',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-79',
        icon: 'i-lucide:sliders-horizontal',
        path: '/sys/config',
      },
      {
        id: 71118,
        title: '系统日志',
        type: 0,
        rootId: 7,
        parentId: 7,
        level: '7-71118',
        icon: 'i-lucide:logs',
        path: '/sys/log',
        children: [
          {
            id: 711181,
            title: '登录日志',
            type: 1,
            rootId: 7,
            parentId: 71118,
            level: '7-71118-711181',
            icon: 'i-lucide:log-in',
            path: '/sys/log/loginLog',
          },
          {
            id: 711182,
            title: '操作日志',
            type: 1,
            rootId: 7,
            parentId: 71118,
            level: '7-71118-711182',
            icon: 'i-lucide:mouse-pointer-click',
            path: '/sys/log/operationLog',
          },
          {
            id: 711183,
            title: '客户端日志',
            type: 1,
            rootId: 7,
            parentId: 71,
            level: '7-71118-711183',
            icon: 'i-lucide:monitor',
            path: '/sys/log/clientLog',
          },
          {
            id: 711184,
            title: '验证码日志',
            type: 1,
            rootId: 7,
            parentId: 71,
            level: '7-71118-711184',
            icon: 'i-lucide:scan-search',
            path: '/sys/log/captchaLog',
          },
        ],
      },
    ],
  },
  {
    id: 8,
    title: '模板中心',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '8',
    icon: 'i-lucide:layout-template',
    children: [
      {
        id: 81,
        title: 'Chat',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-81',
        icon: 'i-lucide:message-square-more',
        path: '/template/chat',
      },
      {
        id: 83,
        title: '日历',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-83',
        icon: 'i-lucide:calendar-days',
        path: '/template/calendar',
      },
      {
        id: 86,
        title: '文档预览',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-86',
        icon: 'i-lucide:file-text',
        path: '/template/document-preview',
        keepAlive: false,
      },
      {
        id: 87,
        title: '定价',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-87',
        icon: 'i-lucide:badge-dollar-sign',
        path: '/template/pricing',
      },
      {
        id: 88,
        title: '低代码设计器',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-88',
        icon: 'i-lucide:blocks',
        path: '/template/low-code',
        keepAlive: false,
      },
      {
        id: 89,
        title: '报表设计器',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-89',
        icon: 'i-lucide:chart-spline',
        path: '/template/report-designer',
        keepAlive: false,
      },
      {
        id: 810,
        title: '图表设计器',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-810',
        icon: 'i-lucide:chart-no-axes-combined',
        path: '/template/chart-designer',
        keepAlive: false,
      },
      {
        id: 811,
        title: '审批流设计器',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-811',
        icon: 'i-lucide:workflow',
        path: '/template/approval-workflow',
        keepAlive: false,
      },
    ],
  },
  {
    id: 82,
    title: '工作流',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '82',
    icon: 'i-lucide:git-branch',
    children: [
      {
        id: 821,
        title: '流程列表',
        type: 1,
        rootId: 82,
        parentId: 82,
        level: '82-821',
        icon: 'i-lucide:list-tree',
        path: '/template/workflow/list',
      },
      {
        id: 822,
        title: '流程监控',
        type: 1,
        rootId: 82,
        parentId: 82,
        level: '82-822',
        icon: 'i-lucide:activity',
        path: '/template/workflow/monitor',
      },
      {
        id: 823,
        title: '流程设计器',
        type: 2,
        rootId: 82,
        parentId: 82,
        level: '82-823',
        icon: 'i-lucide:workflow',
        path: '/template/workflow/designer',
        keepAlive: false,
      },
    ],
  },
  {
    id: 10,
    title: 'Ai开发',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '10',
    icon: 'i-lucide:brain-circuit',
    children: [
      {
        id: 100,
        title: '模型列表',
        type: 1,
        rootId: 10,
        parentId: 10,
        level: '10-100',
        icon: 'i-lucide:cpu',
        path: '/ai-platform/model',
      },
      {
        id: 101,
        title: 'Agent',
        type: 1,
        rootId: 10,
        parentId: 10,
        level: '10-101',
        icon: 'i-lucide:bot',
        path: '/ai-platform/agent',
      },
      {
        id: 1011,
        title: '编辑Agent',
        type: 2,
        rootId: 10,
        parentId: 101,
        level: '10-101-1011',
        icon: 'i-lucide:pencil',
        path: '/ai-platform/agent/edit',
        keepAlive: false,
      },
      {
        id: 102,
        title: 'Chat',
        type: 1,
        rootId: 10,
        parentId: 10,
        level: '10-102',
        icon: 'i-lucide:message-square-more',
        path: '/ai-platform/chart',
      },
      {
        id: 103,
        title: '知识库',
        type: 1,
        rootId: 10,
        parentId: 10,
        level: '10-103',
        icon: 'i-lucide:library-big',
        path: '/ai-platform/knowledge-base',
        componentPath: '/ai-platform/knowledge-base/index',
      },
      {
        id: 1031,
        title: '知识库详情',
        type: 2,
        rootId: 10,
        parentId: 103,
        level: '10-103-1031',
        icon: 'i-lucide:library-big',
        path: '/ai-platform/knowledge-base/detail',
        keepAlive: false,
      },
    ],
  },
  {
    id: 9,
    title: '外部链接',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '9',
    icon: 'i-lucide:external-link',
    children: [
      {
        id: 91,
        title: 'Trae AI',
        type: 1,
        rootId: 9,
        parentId: 9,
        level: '9-91',
        icon: 'i-lucide:globe',
        path: 'https://www.trae.ai',
        isExternal: true,
      },
      {
        id: 92,
        title: 'Ant Design Vue',
        type: 1,
        rootId: 9,
        parentId: 9,
        level: '9-92',
        icon: 'i-lucide:component',
        path: 'https://antdv.com',
        isExternal: true,
      },
      {
        id: 93,
        title: 'Ant Design Vue Next',
        type: 1,
        rootId: 9,
        parentId: 9,
        level: '9-93',
        icon: 'i-lucide:github',
        path: 'https://www.antdv-next.com/index-cn',
        isExternal: true,
      },
    ],
  },

  //   {
  //     id: 2,
  //     title: "权限管理",
  //     type: 0,
  //     parentId: 0,
  //     levelPath: "2",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#f96c17",
  //     children: [
  //       {
  //         id: 21,
  //         title: "后端RBAC权限",
  //         type: 1,
  //         path: "/permission/rbac",
  //         parentId: 0,
  //         levelPath: "2-21",
  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 3,
  //     title: "组件",
  //     type: 0,
  //     path: "/",
  //     parentId: 0,
  //     levelPath: "3",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#62a8fc",
  //     children: [
  //       {
  //         id: 333331111111,
  //         title: "Authority",
  //         type: 1,
  //         path: "/comp/authority",
  //         parentId: 3,
  //         levelPath: "3-333331111111",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 31,
  //         title: "Button",
  //         type: 1,
  //         path: "/comp/button",
  //         parentId: 3,
  //         levelPath: "3-31",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 32,
  //         title: "Watermark",
  //         type: 1,
  //         path: "/comp/watermark",
  //         parentId: 3,
  //         levelPath: "3-32",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 33,
  //         title: "ScrollBar",
  //         type: 1,
  //         path: "/comp/scrollBar",
  //         parentId: 3,
  //         levelPath: "3-33",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 34,
  //         title: "Table",
  //         type: 1,
  //         path: "/comp/table",
  //         parentId: 3,
  //         levelPath: "3-34",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 35,
  //         title: "Form",
  //         type: 1,
  //         path: "/comp/form",
  //         parentId: 3,
  //         levelPath: "3-35",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 36,
  //         title: "Highlight",
  //         type: 1,
  //         path: "/comp/highlight",
  //         parentId: 3,
  //         levelPath: "3-36",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 37,
  //         title: "Example",
  //         type: 1,
  //         path: "/comp/example",
  //         parentId: 3,
  //         levelPath: "3-37",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 38,
  //         title: "VirtualList",
  //         type: 1,
  //         path: "/comp/virtualList",
  //         parentId: 3,
  //         levelPath: "3-38",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 39,
  //         title: "View",
  //         type: 1,
  //         path: "/comp/view",
  //         parentId: 3,
  //         levelPath: "3-39",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999991,
  //         title: "loading",
  //         type: 1,
  //         path: "/comp/loading",
  //         parentId: 3,
  //         levelPath: "3-3999991",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992,
  //         title: "contextMenu",
  //         type: 1,
  //         path: "/comp/contextMenu",
  //         parentId: 3,
  //         levelPath: "3-3999992",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992111,
  //         title: "IconPicker",
  //         type: 1,
  //         path: "/comp/iconPicker",
  //         parentId: 3,
  //         levelPath: "3-3999992111",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992112,
  //         title: "InfiniteScroll",
  //         type: 1,
  //         path: "/comp/infiniteScroll",
  //         parentId: 3,
  //         levelPath: "3-3999992112",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992113,
  //         title: "Time",
  //         type: 1,
  //         path: "/comp/time",
  //         parentId: 3,
  //         levelPath: "3-3999992113",
  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 4999992113,
  //         title: "Dock",
  //         type: 1,
  //         path: "/comp/dock",
  //         parentId: 3,
  //         levelPath: "3-4999992113",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992114,
  //         title: "GradientText(渐变文字)",
  //         type: 1,
  //         path: "/comp/gradientText",
  //         parentId: 3,
  //         levelPath: "3-4999992114",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992115,
  //         title: "Copy",
  //         type: 1,
  //         path: "/comp/copy",
  //         parentId: 3,
  //         levelPath: "3-4999992115",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992116,
  //         title: "Ellipsis",
  //         type: 1,
  //         path: "/comp/ellipsis",
  //         parentId: 3,
  //         levelPath: "3-4999992116",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992117,
  //         title: "ModalPlus",
  //         type: 1,
  //         path: "/comp/modalPlus",
  //         parentId: 3,
  //         levelPath: "3-4999992117",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 4,
  //     title: "Hooks",
  //     type: 0,
  //     path: "",
  //     parentId: 0,
  //     levelPath: "4",
  //     icon: "ri:character-recognition-fill",
  //     iconBgColor: "#737bf2",
  //     children: [
  //       {
  //         id: 41,
  //         title: "useClickOutside",
  //         type: 1,
  //         path: "/hooks/clickOutside",
  //         parentId: 4,
  //         levelPath: "4-41",

  //         icon: "ri:apps-line",
  //       },
  //     ],
  //   },
  //   {
  //     id: 5,
  //     title: "Exception",
  //     type: 0,
  //     path: "5",
  //     parentId: 0,
  //     levelPath: "4",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#52b852",
  //     children: [
  //       {
  //         id: 51,
  //         title: "200(Ok)",
  //         type: 1,
  //         path: "/exception/ok",
  //         parentId: 5,
  //         levelPath: "5-51",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 52,
  //         title: "401(Unauthorized)",
  //         type: 1,
  //         path: "/exception/unauthorized",
  //         parentId: 5,
  //         levelPath: "5-52",

  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 53,
  //         title: "403(Forbidden)",
  //         type: 1,
  //         path: "/exception/forbidden",
  //         parentId: 5,
  //         levelPath: "5-53",

  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 54,
  //         title: "404(NotFound)",
  //         type: 1,
  //         path: "/exception/notFound",
  //         parentId: 5,
  //         levelPath: "5-54",

  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 55,
  //         title: "500(ServerError)",
  //         type: 1,
  //         path: "/exception/serverError",
  //         parentId: 5,
  //         levelPath: "5-55",

  //         icon: "ri:apps-line",
  //       },
  //     ],
  //   },
  //   {
  //     id: 6,
  //     title: "第三方插件",
  //     type: 0,
  //     parentId: 0,
  //     levelPath: "6",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#ff0808",
  //     children: [
  //       {
  //         id: 61,
  //         title: "西瓜播放器",
  //         type: 1,
  //         path: "/plugin/xgplayer",
  //         parentId: 6,
  //         levelPath: "6-61",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 62,
  //         title: "地图",
  //         type: 0,
  //         parentId: 6,
  //         levelPath: "6-62",
  //         icon: "ri:apps-line",
  //         children: [
  //           {
  //             id: 621,
  //             title: "高德地图",
  //             type: 1,
  //             path: "/plugin/map/amap",
  //             parentId: 62,
  //             levelPath: "6-62-611",
  //             icon: "ri:apps-line",
  //           },
  //           {
  //             id: 622,
  //             title: "百度地图",
  //             type: 1,
  //             path: "/plugin/map/bmap",
  //             parentId: 62,
  //             levelPath: "6-62-622",
  //             icon: "ri:apps-line",
  //           },
  //           {
  //             id: 623,
  //             title: "谷歌地图",
  //             type: 1,
  //             path: "/plugin/map/gmap",
  //             parentId: 62,
  //             levelPath: "6-62-623",
  //             icon: "ri:apps-line",
  //           },
  //         ],
  //       },
  //       {
  //         id: 63,
  //         title: "富文本编辑器",
  //         type: 0,
  //         parentId: 6,
  //         levelPath: "6-63",
  //         icon: "ri:apps-line",
  //         children: [
  //           {
  //             id: 631,
  //             title: "plateEditor",
  //             type: 1,
  //             path: "/plugin/editor/plate",
  //             parentId: 63,
  //             levelPath: "6-63-631",
  //             icon: "ri:apps-line",
  //           },
  //           {
  //             id: 632,
  //             title: "AiEditor",
  //             type: 1,
  //             path: "/plugin/editor/ai",
  //             parentId: 63,
  //             levelPath: "6-63-632",
  //             icon: "ri:apps-line",
  //           },
  //         ],
  //       },
  //       {
  //         id: 64,
  //         title: "打字机",
  //         type: 1,
  //         path: "/plugin/typeit",
  //         parentId: 6,
  //         levelPath: "6-64",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 65,
  //         title: "PDF",
  //         type: 1,
  //         path: "/plugin/pdf",
  //         parentId: 6,
  //         levelPath: "6-65",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 66,
  //         title: "Excel",
  //         type: 1,
  //         path: "/plugin/excel",
  //         parentId: 6,
  //         levelPath: "6-66",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 67,
  //         title: "Flow",
  //         type: 0,
  //         parentId: 6,
  //         levelPath: "6-67",
  //         icon: "ri:apps-line",
  //         children: [
  //           {
  //             id: 671,
  //             title: "React-Flow",
  //             type: 1,
  //             parentId: 67,
  //             path: "/plugin/flow/reactFlow",
  //             levelPath: "6-67-671",
  //             icon: "ri:apps-line",
  //             children: [],
  //           },
  //           {
  //             id: 672,
  //             title: "Logic-Flow",
  //             type: 1,
  //             parentId: 67,
  //             path: "/plugin/flow/logicFlow",
  //             levelPath: "6-67-672",
  //             icon: "ri:apps-line",
  //             children: [],
  //           },
  //         ],
  //       },
  //       {
  //         id: 68,
  //         title: "VTable",
  //         type: 1,
  //         path: "/plugin/vtable",
  //         parentId: 6,
  //         levelPath: "6-68",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 69,
  //         title: "瀑布流",
  //         type: 1,
  //         path: "/plugin/waterfall",
  //         parentId: 6,
  //         levelPath: "6-69",
  //         icon: "ri:apps-line",
  //       },
  //     ],
  //   },
  //   {
  //     id: 7,
  //     title: "解决方案",
  //     type: 0,
  //     parentId: 0,
  //     levelPath: "7",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#52b852",
  //     children: [
  //       {
  //         id: 71,
  //         title: "审批流",
  //         type: 1,
  //         parentId: 7,
  //         levelPath: "7-71",
  //         path: "/solution/approvalFlow",
  //         icon: "ri:apps-line",
  //         iconBgColor: "#52b852",
  //       },
  //       {
  //         id: 72,
  //         title: "工作流",
  //         type: 1,
  //         parentId: 7,
  //         levelPath: "7-72",
  //         path: "/solution/workFlow",
  //         icon: "ri:apps-line",
  //         iconBgColor: "#52b852",
  //       },
  //     ],
  //   },
]
