import type { IMenu } from '#/config'

export const menus: IMenu[] = [
  {
    id: 1,
    title: 'Dashboard',
    type: 0,
    path: '/',
    rootId: 0,
    parentId: 0,
    level: '1',
    icon: 'i-lucide:layout-dashboard',
    iconBgColor: '#1677ff',
    iconShape: 'round',
    children: [
      {
        id: 11,
        title: '分析页',
        path: '/dashboard/analysis',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-11',
        home: true,
        keepAlive: true,
      },
      {
        id: 12,
        title: '工作台',
        path: '/dashboard/workbench',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-12',
        keepAlive: true,
      },
      {
        id: 13,
        title: '监控页',
        path: '/dashboard/monitor',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-13',
        keepAlive: true,
      },
      {
        id: 14,
        title: '我的任务',
        path: '/dashboard/task',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-14',
      },
      {
        id: 15,
        title: '文件管理',
        path: '/dashboard/fileManger',
        type: 1,
        rootId: 1,
        parentId: 1,
        level: '1-15',
      },
    ],
  },
  {
    id: 2,
    title: '客户',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '2',
    icon: 'i-lucide:layout-dashboard',
    children: [
      {
        id: 21,
        title: '客户管理',
        type: 0,
        rootId: 2,
        parentId: 2,
        level: '2-21',
        children: [
          {
            id: 211,
            title: '客户管理',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-211',
            path: '/cust/customer/manage',
          },
          {
            id: 212,
            title: '客户属性管理',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-212',
            path: '/customer/customer/customerProp',
          },
          {
            id: 217,
            title: '标签管理',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-217',
            path: '/cust/customer/label',
          },
          {
            id: 213,
            title: '流失客户',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-213',
            path: '/customer/customer/lostCustomer',
          },
          {
            id: 214,
            title: '删人提醒',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-214',
            path: '/customer/customer/deleteReminder',
          },
          {
            id: 215,
            title: '在职继承',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-215',
            path: '/customer/customer/workInherit',
          },
          {
            id: 216,
            title: '离职继承',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-216',
            path: '/customer/customer/resignInherit',
          },
          {
            id: 218,
            title: '黑名单',
            type: 1,
            rootId: 2,
            parentId: 21,
            level: '2-21-218',
            path: '/customer/customer/blackList',
          },
        ],
      },
      {
        id: 22,
        title: '客户群管理',
        type: 0,
        rootId: 2,
        parentId: 2,
        level: '2-22',
        children: [
          {
            id: 221,
            title: '客户群管理',
            type: 1,
            rootId: 2,
            parentId: 22,
            level: '2-22-221',
            path: '/customer/customerGroup/customerGroupManage',
          },
          {
            id: 222,
            title: '客户群标签',
            type: 1,
            rootId: 2,
            parentId: 22,
            level: '2-22-222',
            path: '/customer/customerGroup/customerGroupLabel',
          },
        ],
      },
      {
        id: 23,
        title: '客户属性',
        type: 0,
        rootId: 2,
        parentId: 2,
        level: '2-23',
        children: [
          {
            id: 231,
            title: '客户阶段管理',
            type: 1,
            rootId: 2,
            parentId: 23,
            level: '2-23-231',
            path: '/customer/customerProp/customerStage',
          },
          {
            id: 232,
            title: '自动打标签',
            type: 1,
            rootId: 2,
            parentId: 23,
            level: '2-23-232',
            path: '/customer/customerProp/autoMakeLabel',
          },
        ],
      },
    ],
  },

  {
    id: 3,
    title: '获客',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '3',
    icon: 'i-lucide:layout-dashboard',
    children: [
      {
        id: 31,
        title: '营销获客',
        type: 0,
        rootId: 3,
        parentId: 3,
        level: '3-31',
        children: [
          {
            id: 311,
            title: '渠道活码',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-311',
            path: '/toker/marketing/channelCode',
          },
          {
            id: 312,
            title: '自定义表单',
            type: 1,
            rootId: 3,
            parentId: 31,
            level: '3-31-312',
            path: '/toker/marketing/form',
          },
        ],
      },
      {
        id: 32,
        title: '互动雷达',
        type: 0,
        rootId: 3,
        parentId: 3,
        level: '3-32',
        children: [
          {
            id: 321,
            title: '企业雷达',
            type: 1,
            rootId: 3,
            parentId: 32,
            level: '3-32-321',
            path: '/toker/radar/companyRadar',
          },
          {
            id: 322,
            title: '个人雷达',
            type: 1,
            rootId: 3,
            parentId: 32,
            level: '3-32-322',
            path: '/toker/radar/userRadar',
          },
          {
            id: 323,
            title: '员工雷达记录',
            type: 1,
            rootId: 3,
            parentId: 32,
            level: '3-32-323',
            path: '/toker/radar/radarRecord',
          },
          {
            id: 324,
            title: '数据分析',
            type: 1,
            rootId: 3,
            parentId: 32,
            level: '3-32-324',
            path: '/toker/radar/dataAnalysis',
          },
        ],
      },
    ],
  },

  {
    id: 4,
    title: '运营',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '4',
    icon: 'i-lucide:layout-dashboard',
    children: [
      {
        id: 41,
        title: '客户运营',
        type: 0,
        rootId: 4,
        parentId: 4,
        level: '4-41',
        children: [
          {
            id: 411,
            title: '客户群发',
            type: 1,
            rootId: 4,
            parentId: 41,
            level: '4-41-411',
            path: '/operation/customer/groupSend',
          },
          {
            id: 412,
            title: '客户群群发',
            type: 1,
            rootId: 4,
            parentId: 41,
            level: '4-41-412',
            path: '/operation/customer/groupsSend',
          },
          {
            id: 413,
            title: '好友欢迎语',
            type: 1,
            rootId: 4,
            parentId: 41,
            level: '4-41-413',
            path: '/operation/customer/friendWelcomeMessage',
          },
          {
            id: 414,
            title: '入群欢迎语',
            type: 1,
            rootId: 4,
            parentId: 41,
            level: '4-41-414',
            path: '/operation/customer/joinGroupWelcomeMessage',
          },
          {
            id: 415,
            title: '个人SOP',
            type: 1,
            rootId: 4,
            parentId: 41,
            level: '4-41-415',
            path: '/operation/customer/userSOP',
          },
          {
            id: 416,
            title: '群SOP',
            type: 1,
            rootId: 4,
            parentId: 41,
            level: '4-41-416',
            path: '/operation/customer/groupSOP',
          },
          {
            id: 417,
            title: '企微朋友圈',
            type: 1,
            rootId: 4,
            parentId: 41,
            level: '4-41-417',
            path: '/operation/customer/qwFeed',
          },
        ],
      },
    ],
    path: '',
  },
  {
    id: 5,
    title: '课程',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '5',
    icon: 'i-lucide:layout-dashboard',
    children: [],
    path: '',
  },

  {
    id: 6,
    title: '配置',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '6',
    icon: 'i-lucide:layout-dashboard',
    children: [
      {
        id: 61,
        title: '配置中心',
        type: 0,
        rootId: 6,
        parentId: 6,
        level: '6-61',
        icon: 'i-lucide:layout-dashboard',
        children: [
          {
            id: 611,
            title: '成员管理',
            type: 1,
            rootId: 6,
            parentId: 61,
            level: '6-61-611',
            icon: 'i-lucide:layout-dashboard',
            path: '/config/configCenter/memberManagement',
          },
          {
            id: 612,
            title: '权限管理',
            type: 1,
            rootId: 6,
            parentId: 61,
            level: '6-61-612',
            icon: 'i-lucide:layout-dashboard',
            path: '/config/configCenter/permissionManagement',
          },
          {
            id: 613,
            title: '席位管理',
            type: 1,
            rootId: 6,
            parentId: 61,
            level: '6-61-613',
            icon: 'i-lucide:layout-dashboard',
            path: '/config/configCenter/seatManagement',
          },
          {
            id: 614,
            title: '订单中心',
            type: 1,
            rootId: 6,
            parentId: 61,
            level: '6-61-614',
            icon: 'i-lucide:layout-dashboard',
            path: '/config/configCenter/orderCenter',
          },
          {
            id: 615,
            title: '充值中心',
            type: 1,
            rootId: 6,
            parentId: 61,
            level: '6-61-615',
            icon: 'i-lucide:layout-dashboard',
            path: '/config/configCenter/rechargeCenter',
          },
          {
            id: 616,
            title: '操作日志',
            type: 1,
            rootId: 6,
            parentId: 61,
            level: '6-61-616',
            icon: 'i-lucide:layout-dashboard',
            path: '/config/configCenter/operateLog',
          },
        ],
      },
    ],
  },

  {
    id: 7,
    title: '系统',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '7',
    icon: 'i-lucide:layout-dashboard',
    children: [
      {
        id: 71,
        title: '用户管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-71',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/user',
      },
      {
        id: 72,
        title: '个人中心',
        type: 2,
        rootId: 7,
        parentId: 7,
        level: '7-72',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/userProfile',
      },
      {
        id: 73,
        title: '角色管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-73',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/role',
      },
      {
        id: 74,
        title: '部门管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-74',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/dept',
      },
      {
        id: 75,
        title: '菜单管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-75',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/menu',
      },
      {
        id: 76,
        title: '通知公告',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-76',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/notice',
      },
      {
        id: 77,
        title: '文件管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-77',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/file',
      },
      {
        id: 78,
        title: '字典管理',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-78',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/dict',
      },
      {
        id: 79,
        title: '系统配置',
        type: 1,
        rootId: 7,
        parentId: 7,
        level: '7-79',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/config',
      },
      {
        id: 71118,
        title: '系统日志',
        type: 0,
        rootId: 7,
        parentId: 7,
        level: '7-71118',
        icon: 'i-lucide:layout-dashboard',
        path: '/sys/log',
        children: [
          {
            id: 711181,
            title: '登录日志',
            type: 1,
            rootId: 7,
            parentId: 71118,
            level: '7-71118-711181',
            icon: 'i-lucide:layout-dashboard',
            path: '/sys/log/loginLog',
          },
          {
            id: 711182,
            title: '操作日志',
            type: 1,
            rootId: 7,
            parentId: 71118,
            level: '7-71118-711182',
            icon: 'i-lucide:layout-dashboard',
            path: '/sys/log/operationLog',
          },
          {
            id: 711183,
            title: '客户端日志',
            type: 1,
            rootId: 7,
            parentId: 71,
            level: '7-71118-711183',
            icon: 'i-lucide:layout-dashboard',
            path: '/sys/log/clientLog',
          },
          {
            id: 711184,
            title: '验证码日志',
            type: 1,
            rootId: 7,
            parentId: 71,
            level: '7-71118-711184',
            icon: 'i-lucide:layout-dashboard',
            path: '/sys/log/captchaLog',
          },
        ],
      },
    ],
  },
  {
    id: 8,
    title: '模板中心',
    type: 0,
    rootId: 0,
    parentId: 0,
    level: '8',
    icon: 'i-lucide:layout-dashboard',
    children: [
      {
        id: 81,
        title: 'chat',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-81',
        icon: 'i-lucide:layout-dashboard',
        path: '/template/chat',
      },
      {
        id: 82,
        title: 'workflow',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-82',
        icon: 'i-lucide:layout-dashboard',
        path: '/template/workflow',
      },
      {
        id: 83,
        title: 'calendar',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-83',
        icon: 'i-lucide:layout-dashboard',
        path: '/template/calendar',
      },
      {
        id: 84,
        title: 'editor',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-84',
        icon: 'i-lucide:layout-dashboard',
        path: '/template/editor',
      },
      {
        id: 85,
        title: 'agent',
        type: 1,
        rootId: 8,
        parentId: 8,
        level: '8-85',
        icon: 'i-lucide:layout-dashboard',
        path: '/template/agent',
      },
    ],
  },

  //   {
  //     id: 2,
  //     title: "权限管理",
  //     type: 0,
  //     parentId: 0,
  //     levelPath: "2",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#f96c17",
  //     children: [
  //       {
  //         id: 21,
  //         title: "后端RBAC权限",
  //         type: 1,
  //         path: "/permission/rbac",
  //         parentId: 0,
  //         levelPath: "2-21",
  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 3,
  //     title: "组件",
  //     type: 0,
  //     path: "/",
  //     parentId: 0,
  //     levelPath: "3",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#62a8fc",
  //     children: [
  //       {
  //         id: 333331111111,
  //         title: "Authority",
  //         type: 1,
  //         path: "/comp/authority",
  //         parentId: 3,
  //         levelPath: "3-333331111111",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 31,
  //         title: "Button",
  //         type: 1,
  //         path: "/comp/button",
  //         parentId: 3,
  //         levelPath: "3-31",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 32,
  //         title: "Watermark",
  //         type: 1,
  //         path: "/comp/watermark",
  //         parentId: 3,
  //         levelPath: "3-32",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 33,
  //         title: "ScrollBar",
  //         type: 1,
  //         path: "/comp/scrollBar",
  //         parentId: 3,
  //         levelPath: "3-33",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 34,
  //         title: "Table",
  //         type: 1,
  //         path: "/comp/table",
  //         parentId: 3,
  //         levelPath: "3-34",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 35,
  //         title: "Form",
  //         type: 1,
  //         path: "/comp/form",
  //         parentId: 3,
  //         levelPath: "3-35",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 36,
  //         title: "Highlight",
  //         type: 1,
  //         path: "/comp/highlight",
  //         parentId: 3,
  //         levelPath: "3-36",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 37,
  //         title: "Example",
  //         type: 1,
  //         path: "/comp/example",
  //         parentId: 3,
  //         levelPath: "3-37",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 38,
  //         title: "VirtualList",
  //         type: 1,
  //         path: "/comp/virtualList",
  //         parentId: 3,
  //         levelPath: "3-38",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 39,
  //         title: "View",
  //         type: 1,
  //         path: "/comp/view",
  //         parentId: 3,
  //         levelPath: "3-39",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999991,
  //         title: "loading",
  //         type: 1,
  //         path: "/comp/loading",
  //         parentId: 3,
  //         levelPath: "3-3999991",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992,
  //         title: "contextMenu",
  //         type: 1,
  //         path: "/comp/contextMenu",
  //         parentId: 3,
  //         levelPath: "3-3999992",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992111,
  //         title: "IconPicker",
  //         type: 1,
  //         path: "/comp/iconPicker",
  //         parentId: 3,
  //         levelPath: "3-3999992111",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992112,
  //         title: "InfiniteScroll",
  //         type: 1,
  //         path: "/comp/infiniteScroll",
  //         parentId: 3,
  //         levelPath: "3-3999992112",

  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 3999992113,
  //         title: "Time",
  //         type: 1,
  //         path: "/comp/time",
  //         parentId: 3,
  //         levelPath: "3-3999992113",
  //         icon: "ri:apps-line",
  //         children: [],
  //       },
  //       {
  //         id: 4999992113,
  //         title: "Dock",
  //         type: 1,
  //         path: "/comp/dock",
  //         parentId: 3,
  //         levelPath: "3-4999992113",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992114,
  //         title: "GradientText(渐变文字)",
  //         type: 1,
  //         path: "/comp/gradientText",
  //         parentId: 3,
  //         levelPath: "3-4999992114",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992115,
  //         title: "Copy",
  //         type: 1,
  //         path: "/comp/copy",
  //         parentId: 3,
  //         levelPath: "3-4999992115",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992116,
  //         title: "Ellipsis",
  //         type: 1,
  //         path: "/comp/ellipsis",
  //         parentId: 3,
  //         levelPath: "3-4999992116",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //       {
  //         id: 4999992117,
  //         title: "ModalPlus",
  //         type: 1,
  //         path: "/comp/modalPlus",
  //         parentId: 3,
  //         levelPath: "3-4999992117",
  //         icon: "ri:character-recognition-fill",
  //         children: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 4,
  //     title: "Hooks",
  //     type: 0,
  //     path: "",
  //     parentId: 0,
  //     levelPath: "4",
  //     icon: "ri:character-recognition-fill",
  //     iconBgColor: "#737bf2",
  //     children: [
  //       {
  //         id: 41,
  //         title: "useClickOutside",
  //         type: 1,
  //         path: "/hooks/clickOutside",
  //         parentId: 4,
  //         levelPath: "4-41",

  //         icon: "ri:apps-line",
  //       },
  //     ],
  //   },
  //   {
  //     id: 5,
  //     title: "Exception",
  //     type: 0,
  //     path: "5",
  //     parentId: 0,
  //     levelPath: "4",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#52b852",
  //     children: [
  //       {
  //         id: 51,
  //         title: "200(Ok)",
  //         type: 1,
  //         path: "/exception/ok",
  //         parentId: 5,
  //         levelPath: "5-51",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 52,
  //         title: "401(Unauthorized)",
  //         type: 1,
  //         path: "/exception/unauthorized",
  //         parentId: 5,
  //         levelPath: "5-52",

  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 53,
  //         title: "403(Forbidden)",
  //         type: 1,
  //         path: "/exception/forbidden",
  //         parentId: 5,
  //         levelPath: "5-53",

  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 54,
  //         title: "404(NotFound)",
  //         type: 1,
  //         path: "/exception/notFound",
  //         parentId: 5,
  //         levelPath: "5-54",

  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 55,
  //         title: "500(ServerError)",
  //         type: 1,
  //         path: "/exception/serverError",
  //         parentId: 5,
  //         levelPath: "5-55",

  //         icon: "ri:apps-line",
  //       },
  //     ],
  //   },
  //   {
  //     id: 6,
  //     title: "第三方插件",
  //     type: 0,
  //     parentId: 0,
  //     levelPath: "6",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#ff0808",
  //     children: [
  //       {
  //         id: 61,
  //         title: "西瓜播放器",
  //         type: 1,
  //         path: "/plugin/xgplayer",
  //         parentId: 6,
  //         levelPath: "6-61",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 62,
  //         title: "地图",
  //         type: 0,
  //         parentId: 6,
  //         levelPath: "6-62",
  //         icon: "ri:apps-line",
  //         children: [
  //           {
  //             id: 621,
  //             title: "高德地图",
  //             type: 1,
  //             path: "/plugin/map/amap",
  //             parentId: 62,
  //             levelPath: "6-62-611",
  //             icon: "ri:apps-line",
  //           },
  //           {
  //             id: 622,
  //             title: "百度地图",
  //             type: 1,
  //             path: "/plugin/map/bmap",
  //             parentId: 62,
  //             levelPath: "6-62-622",
  //             icon: "ri:apps-line",
  //           },
  //           {
  //             id: 623,
  //             title: "谷歌地图",
  //             type: 1,
  //             path: "/plugin/map/gmap",
  //             parentId: 62,
  //             levelPath: "6-62-623",
  //             icon: "ri:apps-line",
  //           },
  //         ],
  //       },
  //       {
  //         id: 63,
  //         title: "富文本编辑器",
  //         type: 0,
  //         parentId: 6,
  //         levelPath: "6-63",
  //         icon: "ri:apps-line",
  //         children: [
  //           {
  //             id: 631,
  //             title: "plateEditor",
  //             type: 1,
  //             path: "/plugin/editor/plate",
  //             parentId: 63,
  //             levelPath: "6-63-631",
  //             icon: "ri:apps-line",
  //           },
  //           {
  //             id: 632,
  //             title: "AiEditor",
  //             type: 1,
  //             path: "/plugin/editor/ai",
  //             parentId: 63,
  //             levelPath: "6-63-632",
  //             icon: "ri:apps-line",
  //           },
  //         ],
  //       },
  //       {
  //         id: 64,
  //         title: "打字机",
  //         type: 1,
  //         path: "/plugin/typeit",
  //         parentId: 6,
  //         levelPath: "6-64",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 65,
  //         title: "PDF",
  //         type: 1,
  //         path: "/plugin/pdf",
  //         parentId: 6,
  //         levelPath: "6-65",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 66,
  //         title: "Excel",
  //         type: 1,
  //         path: "/plugin/excel",
  //         parentId: 6,
  //         levelPath: "6-66",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 67,
  //         title: "Flow",
  //         type: 0,
  //         parentId: 6,
  //         levelPath: "6-67",
  //         icon: "ri:apps-line",
  //         children: [
  //           {
  //             id: 671,
  //             title: "React-Flow",
  //             type: 1,
  //             parentId: 67,
  //             path: "/plugin/flow/reactFlow",
  //             levelPath: "6-67-671",
  //             icon: "ri:apps-line",
  //             children: [],
  //           },
  //           {
  //             id: 672,
  //             title: "Logic-Flow",
  //             type: 1,
  //             parentId: 67,
  //             path: "/plugin/flow/logicFlow",
  //             levelPath: "6-67-672",
  //             icon: "ri:apps-line",
  //             children: [],
  //           },
  //         ],
  //       },
  //       {
  //         id: 68,
  //         title: "VTable",
  //         type: 1,
  //         path: "/plugin/vtable",
  //         parentId: 6,
  //         levelPath: "6-68",
  //         icon: "ri:apps-line",
  //       },
  //       {
  //         id: 69,
  //         title: "瀑布流",
  //         type: 1,
  //         path: "/plugin/waterfall",
  //         parentId: 6,
  //         levelPath: "6-69",
  //         icon: "ri:apps-line",
  //       },
  //     ],
  //   },
  //   {
  //     id: 7,
  //     title: "解决方案",
  //     type: 0,
  //     parentId: 0,
  //     levelPath: "7",
  //     icon: "ri:apps-line",
  //     iconBgColor: "#52b852",
  //     children: [
  //       {
  //         id: 71,
  //         title: "审批流",
  //         type: 1,
  //         parentId: 7,
  //         levelPath: "7-71",
  //         path: "/solution/approvalFlow",
  //         icon: "ri:apps-line",
  //         iconBgColor: "#52b852",
  //       },
  //       {
  //         id: 72,
  //         title: "工作流",
  //         type: 1,
  //         parentId: 7,
  //         levelPath: "7-72",
  //         path: "/solution/workFlow",
  //         icon: "ri:apps-line",
  //         iconBgColor: "#52b852",
  //       },
  //     ],
  //   },
]
