import type { IMenu } from '#/config'

export const menus: IMenu[] = [
  {
    id: '1',
    title: 'Dashboard',
    type: 0,
    path: '/',
    rootId: '0',
    parentId: '0',
    level: '1',
    icon: 'i-lucide:layout-dashboard',
    iconBgColor: '#1677ff',
    iconShape: 'round',
    children: [
      {
        id: '11',
        title: '分析页',
        path: '/dashboard/analysis',
        type: 1,
        rootId: '1',
        parentId: '1',
        level: '1-11',
        icon: 'i-lucide:chart-no-axes-combined',
        home: true,
        keepAlive: true,
      },
      {
        id: '12',
        title: '工作台',
        path: '/dashboard/workbench',
        type: 1,
        rootId: '1',
        parentId: '1',
        level: '1-12',
        icon: 'i-lucide:briefcase-business',
        keepAlive: true,
      },
      {
        id: '13',
        title: '监控页',
        path: '/dashboard/monitor',
        type: 1,
        rootId: '1',
        parentId: '1',
        level: '1-13',
        icon: 'i-lucide:activity',
        keepAlive: true,
      },
      {
        id: '14',
        title: '我的任务',
        path: '/dashboard/task',
        type: 1,
        rootId: '1',
        parentId: '1',
        level: '1-14',
        icon: 'i-lucide:list-checks',
      },
      {
        id: '15',
        title: '文件管理',
        path: '/dashboard/fileManger',
        type: 1,
        rootId: '1',
        parentId: '1',
        level: '1-15',
        icon: 'i-lucide:folder-open',
      },
      {
        id: '16',
        title: '工单',
        type: 0,
        rootId: '1',
        parentId: '1',
        level: '1-16',
        icon: 'i-lucide:ticket-check',
        children: [
          {
            id: '161',
            title: '工单中心',
            path: '/dashboard/ticket/center',
            type: 1,
            rootId: '1',
            parentId: '16',
            level: '1-16-161',
            icon: 'i-lucide:ticket-check',
          },
          {
            id: '162',
            title: '工单处理',
            path: '/dashboard/ticket/management',
            type: 1,
            rootId: '1',
            parentId: '16',
            level: '1-16-162',
            icon: 'i-lucide:headset',
          },
        ],
      },
    ],
  },
  {
    id: '3',
    title: '组件',
    type: 0,
    rootId: '0',
    parentId: '0',
    level: '3',
    icon: 'i-lucide:blocks',
    children: [
      {
        id: '31',
        title: '基础能力',
        type: 0,
        rootId: '3',
        parentId: '3',
        level: '3-31',
        icon: 'i-lucide:blocks',
        children: [
          {
            id: '311',
            title: 'Icon',
            type: 1,
            rootId: '3',
            parentId: '31',
            level: '3-31-311',
            icon: 'i-lucide:shapes',
            path: '/component/icon',
          },
          {
            id: '312',
            title: 'Loading',
            type: 1,
            rootId: '3',
            parentId: '31',
            level: '3-31-312',
            icon: 'i-lucide:loader-circle',
            path: '/component/loading',
          },
          {
            id: '313',
            title: 'NumberTicker',
            type: 1,
            rootId: '3',
            parentId: '31',
            level: '3-31-313',
            icon: 'i-lucide:chart-no-axes-column-increasing',
            path: '/component/number-ticker',
          },
          {
            id: '314',
            title: 'WView',
            type: 1,
            rootId: '3',
            parentId: '31',
            level: '3-31-314',
            icon: 'i-lucide:panel-top',
            path: '/component/view',
          },
          {
            id: '315',
            title: 'Scrollbar',
            type: 1,
            rootId: '3',
            parentId: '31',
            level: '3-31-315',
            icon: 'i-lucide:gallery-vertical-end',
            path: '/component/scrollbar',
          },
          {
            id: '316',
            title: 'Container',
            type: 1,
            rootId: '3',
            parentId: '31',
            level: '3-31-316',
            icon: 'i-lucide:panels-top-left',
            path: '/component/container',
          },
        ],
      },
      {
        id: '32',
        title: '输入与选择',
        type: 0,
        rootId: '3',
        parentId: '3',
        level: '3-32',
        icon: 'i-lucide:mouse-pointer-click',
        children: [
          {
            id: '321',
            title: 'IconSelector',
            type: 1,
            rootId: '3',
            parentId: '32',
            level: '3-32-321',
            icon: 'i-lucide:grid-2x2',
            path: '/component/icon-selector',
          },
          {
            id: '322',
            title: 'IconPicker',
            type: 1,
            rootId: '3',
            parentId: '32',
            level: '3-32-322',
            icon: 'i-lucide:mouse-pointer-click',
            path: '/component/icon-picker',
          },
          {
            id: '323',
            title: 'DatePicker',
            type: 1,
            rootId: '3',
            parentId: '32',
            level: '3-32-323',
            icon: 'i-lucide:calendar-days',
            path: '/component/date-picker',
          },
        ],
      },
      {
        id: '33',
        title: '数据展示',
        type: 0,
        rootId: '3',
        parentId: '3',
        level: '3-33',
        icon: 'i-lucide:braces',
        children: [
          {
            id: '331',
            title: 'CodeEditor',
            type: 1,
            rootId: '3',
            parentId: '33',
            level: '3-33-331',
            icon: 'i-lucide:braces',
            path: '/component/code-editor',
          },
          {
            id: '332',
            title: 'JsonView',
            type: 1,
            rootId: '3',
            parentId: '33',
            level: '3-33-332',
            icon: 'i-lucide:file-json-2',
            path: '/component/json-view',
          },
          {
            id: '333',
            title: 'Exception',
            type: 1,
            rootId: '3',
            parentId: '33',
            level: '3-33-333',
            icon: 'i-lucide:circle-alert',
            path: '/component/exception',
          },
          {
            id: '334',
            title: 'FilePreview',
            type: 1,
            rootId: '3',
            parentId: '33',
            level: '3-33-334',
            icon: 'i-lucide:file-search',
            path: '/component/file-preview',
          },
        ],
      },
      {
        id: '34',
        title: '交互组件',
        type: 0,
        rootId: '3',
        parentId: '3',
        level: '3-34',
        icon: 'i-lucide:hand',
        children: [
          {
            id: '342',
            title: 'Draggable',
            type: 1,
            rootId: '3',
            parentId: '34',
            level: '3-34-342',
            icon: 'i-lucide:grip-vertical',
            path: '/component/draggable',
          },
          {
            id: '343',
            title: 'Modal',
            type: 1,
            rootId: '3',
            parentId: '34',
            level: '3-34-343',
            icon: 'i-lucide:panels-top-left',
            path: '/component/modal',
          },
        ],
      },
      {
        id: '35',
        title: '重型组件',
        type: 0,
        rootId: '3',
        parentId: '3',
        level: '3-35',
        icon: 'i-lucide:boxes',
        children: [
          {
            id: '351',
            title: 'Editor',
            type: 1,
            rootId: '3',
            parentId: '35',
            level: '3-35-351',
            icon: 'i-lucide:notebook-pen',
            path: '/component/editor',
            keepAlive: false,
          },
          {
            id: '352',
            title: 'Cropper',
            type: 1,
            rootId: '3',
            parentId: '35',
            level: '3-35-352',
            icon: 'i-lucide:crop',
            path: '/component/cropper',
            keepAlive: false,
          },
          {
            id: '353',
            title: 'Gantt',
            type: 1,
            rootId: '3',
            parentId: '35',
            level: '3-35-353',
            icon: 'i-lucide:gantt-chart',
            path: '/component/gantt',
            keepAlive: false,
          },
          {
            id: '354',
            title: 'ErrorBoundary',
            type: 1,
            rootId: '3',
            parentId: '35',
            level: '3-35-354',
            icon: 'i-lucide:shield-alert',
            path: '/component/error-boundary',
          },
        ],
      },
    ],
  },

  {
    id: '6',
    title: '文章管理',
    type: 0,
    rootId: '0',
    parentId: '0',
    level: '6',
    icon: 'i-lucide:newspaper',
    children: [
      {
        id: '61',
        title: '文章列表',
        type: 1,
        rootId: '6',
        parentId: '6',
        level: '6-61',
        icon: 'i-lucide:files',
        path: '/article/list',
        children: [
          {
            id: '611',
            title: '文章编辑',
            type: 2,
            rootId: '6',
            parentId: '61',
            level: '6-61-611',
            icon: 'i-lucide:file-pen-line',
            path: '/article/editor',
            keepAlive: false,
          },
        ],
      },
    ],
  },

  {
    id: '7',
    title: '系统',
    type: 0,
    rootId: '0',
    parentId: '0',
    level: '7',
    icon: 'i-lucide:cog',
    children: [
      {
        id: '71',
        title: '用户管理',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-71',
        icon: 'i-lucide:users',
        path: '/sys/user',
      },
      {
        id: '72',
        title: '个人中心',
        type: 2,
        rootId: '7',
        parentId: '7',
        level: '7-72',
        icon: 'i-lucide:id-card',
        path: '/sys/userProfile',
      },
      {
        id: '73',
        title: '角色管理',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-73',
        icon: 'i-lucide:shield-check',
        path: '/sys/role',
      },
      {
        id: '74',
        title: '部门管理',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-74',
        icon: 'i-lucide:building-2',
        path: '/sys/dept',
      },
      {
        id: '75',
        title: '菜单管理',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-75',
        icon: 'i-lucide:menu',
        path: '/sys/menu',
      },
      {
        id: '76',
        title: '通知公告',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-76',
        icon: 'i-lucide:bell',
        path: '/sys/notice',
      },
      {
        id: '77',
        title: '文件管理',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-77',
        icon: 'i-lucide:file',
        path: '/sys/file',
      },
      {
        id: '78',
        title: '字典管理',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-78',
        icon: 'i-lucide:book-type',
        path: '/sys/dict',
      },
      {
        id: '79',
        title: '系统配置',
        type: 1,
        rootId: '7',
        parentId: '7',
        level: '7-79',
        icon: 'i-lucide:sliders-horizontal',
        path: '/sys/config',
      },
      {
        id: '71118',
        title: '系统日志',
        type: 0,
        rootId: '7',
        parentId: '7',
        level: '7-71118',
        icon: 'i-lucide:logs',
        path: '/sys/log',
        children: [
          {
            id: '711181',
            title: '登录日志',
            type: 1,
            rootId: '7',
            parentId: '71118',
            level: '7-71118-711181',
            icon: 'i-lucide:log-in',
            path: '/sys/log/loginLog',
          },
          {
            id: '711182',
            title: '操作日志',
            type: 1,
            rootId: '7',
            parentId: '71118',
            level: '7-71118-711182',
            icon: 'i-lucide:mouse-pointer-click',
            path: '/sys/log/operationLog',
          },
          {
            id: '711183',
            title: '客户端日志',
            type: 1,
            rootId: '7',
            parentId: '71118',
            level: '7-71118-711183',
            icon: 'i-lucide:monitor',
            path: '/sys/log/clientLog',
          },
          {
            id: '711184',
            title: '验证码日志',
            type: 1,
            rootId: '7',
            parentId: '71118',
            level: '7-71118-711184',
            icon: 'i-lucide:scan-search',
            path: '/sys/log/captchaLog',
          },
        ],
      },
    ],
  },
  {
    id: '8',
    title: '模板中心',
    type: 0,
    rootId: '0',
    parentId: '0',
    level: '8',
    icon: 'i-lucide:layout-template',
    children: [
      {
        id: '81',
        title: 'Chat',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-81',
        icon: 'i-lucide:message-square-more',
        path: '/template/chat',
      },
      {
        id: '83',
        title: '日历',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-83',
        icon: 'i-lucide:calendar-days',
        path: '/template/calendar',
      },
      {
        id: '86',
        title: '文档预览',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-86',
        icon: 'i-lucide:file-text',
        path: '/template/document-preview',
        keepAlive: false,
      },
      {
        id: '87',
        title: '定价',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-87',
        icon: 'i-lucide:badge-dollar-sign',
        path: '/template/pricing',
      },
      {
        id: '88',
        title: '低代码设计器',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-88',
        icon: 'i-lucide:blocks',
        path: '/template/low-code',
        keepAlive: false,
      },
      {
        id: '89',
        title: '报表设计器',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-89',
        icon: 'i-lucide:chart-spline',
        path: '/template/report-designer',
        keepAlive: false,
      },
      {
        id: '810',
        title: '图表设计器',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-810',
        icon: 'i-lucide:chart-no-axes-combined',
        path: '/template/chart-designer',
        keepAlive: false,
      },
      {
        id: '811',
        title: '审批流设计器',
        type: 1,
        rootId: '8',
        parentId: '8',
        level: '8-811',
        icon: 'i-lucide:workflow',
        path: '/template/approval-workflow',
        keepAlive: false,
      },
    ],
  },
  {
    id: '82',
    title: '工作流',
    type: 0,
    rootId: '0',
    parentId: '0',
    level: '82',
    icon: 'i-lucide:git-branch',
    children: [
      {
        id: '821',
        title: '流程列表',
        type: 1,
        rootId: '82',
        parentId: '82',
        level: '82-821',
        icon: 'i-lucide:list-tree',
        path: '/template/workflow/list',
      },
      {
        id: '822',
        title: '流程监控',
        type: 1,
        rootId: '82',
        parentId: '82',
        level: '82-822',
        icon: 'i-lucide:activity',
        path: '/template/workflow/monitor',
      },
      {
        id: '823',
        title: '流程设计器',
        type: 2,
        rootId: '82',
        parentId: '82',
        level: '82-823',
        icon: 'i-lucide:workflow',
        path: '/template/workflow/designer',
        keepAlive: false,
      },
    ],
  },
  {
    id: '10',
    title: 'Ai开发',
    type: 0,
    rootId: '0',
    parentId: '0',
    level: '10',
    icon: 'i-lucide:brain-circuit',
    children: [
      {
        id: '100',
        title: '模型列表',
        type: 1,
        rootId: '10',
        parentId: '10',
        level: '10-100',
        icon: 'i-lucide:cpu',
        path: '/ai-platform/model',
      },
      {
        id: '101',
        title: 'Agent',
        type: 1,
        rootId: '10',
        parentId: '10',
        level: '10-101',
        icon: 'i-lucide:bot',
        path: '/ai-platform/agent',
        children: [
          {
            id: '1011',
            title: '编辑Agent',
            type: 2,
            rootId: '10',
            parentId: '101',
            level: '10-101-1011',
            icon: 'i-lucide:pencil',
            path: '/ai-platform/agent/edit',
            keepAlive: false,
          },
        ],
      },
      {
        id: '102',
        title: 'Chat',
        type: 1,
        rootId: '10',
        parentId: '10',
        level: '10-102',
        icon: 'i-lucide:message-square-more',
        path: '/ai-platform/chart',
      },
      {
        id: '103',
        title: '知识库',
        type: 1,
        rootId: '10',
        parentId: '10',
        level: '10-103',
        icon: 'i-lucide:library-big',
        path: '/ai-platform/knowledge-base',
        children: [
          {
            id: '1031',
            title: '知识库详情',
            type: 2,
            rootId: '10',
            parentId: '103',
            level: '10-103-1031',
            icon: 'i-lucide:library-big',
            path: '/ai-platform/knowledge-base/detail',
            keepAlive: false,
          },
        ],
      },
    ],
  },
  {
    id: '9',
    title: '外部链接',
    type: 0,
    rootId: '0',
    parentId: '0',
    level: '9',
    icon: 'i-lucide:external-link',
    children: [
      {
        id: '91',
        title: 'Trae AI',
        type: 1,
        rootId: '9',
        parentId: '9',
        level: '9-91',
        icon: 'i-lucide:globe',
        path: 'https://www.trae.ai',
        isExternal: true,
      },
      {
        id: '92',
        title: 'Ant Design Vue',
        type: 1,
        rootId: '9',
        parentId: '9',
        level: '9-92',
        icon: 'i-lucide:component',
        path: 'https://antdv.com',
        isExternal: true,
      },
      {
        id: '93',
        title: 'Ant Design Vue Next',
        type: 1,
        rootId: '9',
        parentId: '9',
        level: '9-93',
        icon: 'i-lucide:github',
        path: 'https://www.antdv-next.com/index-cn',
        isExternal: true,
      },
    ],
  },
]
