import type { ChartCatalogItem } from './types'

export const advancedChartControls = [
  {
    type: 'funnel',
    kind: 'chart',
    title: '转化漏斗',
    description: '适合线索、销售和流程转化',
    icon: 'i-lucide:funnel',
    defaultColSpan: 5,
    defaultRowSpan: 2,
  },
  {
    type: 'scatter',
    kind: 'chart',
    title: '散点分布',
    description: '适合离散指标、异常点和分布分析',
    icon: 'i-lucide:chart-scatter',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'radar',
    kind: 'chart',
    title: '雷达对比',
    description: '适合多维能力、服务健康度和画像评分',
    icon: 'i-lucide:radar',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'gauge',
    kind: 'chart',
    title: '仪表盘',
    description: '适合健康度、达成率和关键阈值',
    icon: 'i-lucide:gauge',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'heatmap',
    kind: 'chart',
    title: '热力图',
    description: '适合密度、热度和峰值区间观察',
    icon: 'i-lucide:grid-3x3',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'treemap',
    kind: 'chart',
    title: '矩形树图',
    description: '适合结构占比、资源分布和层级规模',
    icon: 'i-lucide:layout-grid',
    defaultColSpan: 5,
    defaultRowSpan: 2,
  },
  {
    type: 'sunburst',
    kind: 'chart',
    title: '旭日图',
    description: '适合层级结构、路径拆解和多层占比',
    icon: 'i-lucide:circle-dot',
    defaultColSpan: 5,
    defaultRowSpan: 2,
  },
  {
    type: 'boxplot',
    kind: 'chart',
    title: '箱线图',
    description: '适合分布区间、异常值和波动范围',
    icon: 'i-lucide:chart-candlestick',
    defaultColSpan: 5,
    defaultRowSpan: 2,
  },
  {
    type: 'candlestick',
    kind: 'chart',
    title: 'K线图',
    description: '适合价格走势、开收盘和区间分析',
    icon: 'i-lucide:chart-candlestick',
    defaultColSpan: 5,
    defaultRowSpan: 2,
  },
  {
    type: 'graph',
    kind: 'chart',
    title: '关系图',
    description: '适合实体关系、链路拓扑和关联网络',
    icon: 'i-lucide:network',
    defaultColSpan: 5,
    defaultRowSpan: 2,
  },
  {
    type: 'pictorialBar',
    kind: 'chart',
    title: '象形柱图',
    description: '适合排名、目标完成和视觉化指标',
    icon: 'i-lucide:chart-no-axes-column-increasing',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'sankey',
    kind: 'chart',
    title: '桑基图',
    description: '适合流向、转化路径和资源分配',
    icon: 'i-lucide:git-branch',
    defaultColSpan: 6,
    defaultRowSpan: 2,
  },
] satisfies readonly ChartCatalogItem[]
