import type { ChartCatalogItem } from './types'

export const basicChartControls = [
  {
    type: 'kpi',
    kind: 'kpi',
    title: '指标卡',
    description: '展示核心指标、同比和状态',
    icon: 'i-lucide:gauge',
    defaultColSpan: 3,
    defaultRowSpan: 1,
  },
  {
    type: 'area',
    kind: 'chart',
    title: '趋势面积图',
    description: '适合趋势、增长和峰值观察',
    icon: 'i-lucide:chart-area',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'bar',
    kind: 'chart',
    title: '排行柱状图',
    description: '适合分类对比和 Top 分析',
    icon: 'i-lucide:chart-column',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'line',
    kind: 'chart',
    title: '折线趋势',
    description: '适合连续变化、周期趋势和目标追踪',
    icon: 'i-lucide:chart-line',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'pie',
    kind: 'chart',
    title: '占比环图',
    description: '适合渠道、区域和结构占比',
    icon: 'i-lucide:chart-pie',
    defaultColSpan: 4,
    defaultRowSpan: 2,
  },
  {
    type: 'table',
    kind: 'table',
    title: '明细表格',
    description: '展示最新数据和异常明细',
    icon: 'i-lucide:table-2',
    defaultColSpan: 8,
    defaultRowSpan: 2,
  },
  {
    type: 'note',
    kind: 'note',
    title: 'AI 洞察',
    description: '沉淀图表结论和行动建议',
    icon: 'i-lucide:sparkles',
    defaultColSpan: 5,
    defaultRowSpan: 2,
  },
] satisfies readonly ChartCatalogItem[]
