import {
  booleanField,
  numberField,
  optionList,
  optionsField,
  selectField,
  textField,
  textareaField,
  type AnyControlDefinition,
} from './controlUtils.ts'

const commonStyle = {
  density: 'comfortable',
  gridColumn: 6,
  tone: 'neutral',
} as const

const fullStyle = {
  density: 'comfortable',
  gridColumn: 12,
  tone: 'neutral',
} as const

export const antdControlDefinitions = [
  {
    type: 'input',
    category: 'antd',
    title: 'Input',
    description: '文本输入、搜索和前后缀。',
    icon: 'i-lucide:text-cursor-input',
    badge: 'Antdv',
    defaultProps: {
      allowClear: true,
      placeholder: '请输入内容',
      prefixIcon: 'i-lucide:search',
      value: '',
    },
    defaultStyle: commonStyle,
    fields: [
      textField('placeholder', '占位提示'),
      textField('value', '默认值'),
      textField('prefixIcon', '前缀图标'),
      booleanField('allowClear', '允许清空'),
    ],
  },
  {
    type: 'textarea',
    category: 'antd',
    title: 'Textarea',
    description: '多行文本输入和备注。',
    icon: 'i-lucide:align-left',
    badge: 'Antdv',
    defaultProps: { placeholder: '请输入备注', rows: 4, value: '' },
    defaultStyle: fullStyle,
    fields: [
      textField('placeholder', '占位提示'),
      textareaField('value', '默认值'),
      numberField('rows', '行数'),
    ],
  },
  {
    type: 'inputNumber',
    category: 'antd',
    title: 'InputNumber',
    description: '金额、数量和比例输入。',
    icon: 'i-lucide:circle-dollar-sign',
    badge: 'Antdv',
    defaultProps: { max: 999, min: 0, prefix: '¥', step: 1, value: 128 },
    defaultStyle: commonStyle,
    fields: [
      numberField('value', '默认值'),
      numberField('min', '最小值'),
      numberField('max', '最大值'),
      numberField('step', '步长'),
      textField('prefix', '前缀'),
    ],
  },
  {
    type: 'select',
    category: 'antd',
    title: 'Select',
    description: '枚举、状态和成员选择。',
    icon: 'i-lucide:list-filter',
    badge: 'Antdv',
    defaultProps: {
      mode: 'default',
      options: optionList(['待处理', '进行中', '已完成']),
      placeholder: '请选择状态',
      value: '进行中',
    },
    defaultStyle: commonStyle,
    fields: [
      textField('placeholder', '占位提示'),
      selectField('mode', '选择模式', [
        { label: '单选', value: 'default' },
        { label: '多选', value: 'multiple' },
        { label: '标签', value: 'tags' },
      ]),
      optionsField('options', '选项'),
    ],
  },
  {
    type: 'radioGroup',
    category: 'antd',
    title: 'RadioGroup',
    description: '少量可见选项的单选。',
    icon: 'i-lucide:list-checks',
    badge: 'Antdv',
    defaultProps: {
      buttonStyle: 'solid',
      optionType: 'button',
      options: optionList(['日', '周', '月']),
      value: '周',
    },
    defaultStyle: commonStyle,
    fields: [
      optionsField('options', '选项'),
      selectField('optionType', '选项样式', [
        { label: '默认', value: 'default' },
        { label: '按钮', value: 'button' },
      ]),
      selectField('buttonStyle', '按钮风格', [
        { label: '描边', value: 'outline' },
        { label: '填充', value: 'solid' },
      ]),
    ],
  },
  {
    type: 'checkbox',
    category: 'antd',
    title: 'Checkbox',
    description: '布尔确认和协议勾选。',
    icon: 'i-lucide:square-check',
    badge: 'Antdv',
    defaultProps: { checked: true, label: '启用自动同步' },
    defaultStyle: commonStyle,
    fields: [textField('label', '标签'), booleanField('checked', '已勾选')],
  },
  {
    type: 'switch',
    category: 'antd',
    title: 'Switch',
    description: '开启/关闭类配置。',
    icon: 'i-lucide:toggle-right',
    badge: 'Antdv',
    defaultProps: { checked: true, checkedText: '开', uncheckedText: '关' },
    defaultStyle: commonStyle,
    fields: [
      booleanField('checked', '已开启'),
      textField('checkedText', '开启文案'),
      textField('uncheckedText', '关闭文案'),
    ],
  },
  {
    type: 'slider',
    category: 'antd',
    title: 'Slider',
    description: '百分比、阈值和范围调节。',
    icon: 'i-lucide:sliders-horizontal',
    badge: 'Antdv',
    defaultProps: { max: 100, min: 0, step: 5, value: 65 },
    defaultStyle: commonStyle,
    fields: [
      numberField('value', '默认值'),
      numberField('min', '最小值'),
      numberField('max', '最大值'),
      numberField('step', '步长'),
    ],
  },
  {
    type: 'rate',
    category: 'antd',
    title: 'Rate',
    description: '评分、满意度和等级展示。',
    icon: 'i-lucide:star',
    badge: 'Antdv',
    defaultProps: { allowHalf: true, count: 5, value: 4.5 },
    defaultStyle: commonStyle,
    fields: [
      numberField('value', '默认值'),
      numberField('count', '星级数量'),
      booleanField('allowHalf', '允许半星'),
    ],
  },
  {
    type: 'datePicker',
    category: 'antd',
    title: 'DatePicker',
    description: '日期、月份、周和年份选择。',
    icon: 'i-lucide:calendar-days',
    badge: 'Antdv',
    defaultProps: { picker: 'date', placeholder: '选择日期' },
    defaultStyle: commonStyle,
    fields: [
      textField('placeholder', '占位提示'),
      selectField('picker', '日期粒度', [
        { label: '日期', value: 'date' },
        { label: '月份', value: 'month' },
        { label: '周', value: 'week' },
        { label: '年份', value: 'year' },
      ]),
    ],
  },
  {
    type: 'image',
    category: 'antd',
    title: 'Image',
    description: '图片展示和预览。',
    icon: 'i-lucide:image',
    badge: 'Antdv',
    defaultProps: {
      alt: '低代码图片',
      height: 140,
      preview: true,
      src: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',
      width: 240,
    },
    defaultStyle: commonStyle,
    fields: [
      textField('src', '图片地址'),
      textField('alt', '替代文本'),
      numberField('width', '宽度'),
      numberField('height', '高度'),
      booleanField('preview', '允许预览'),
    ],
  },
] satisfies readonly AnyControlDefinition[]
