import { Menu } from '/@/router/types';

export const menus: Menu[] = [
  {
    id: 1,
    type: 1,
    parent_id: null,
    name: 'Dashboard',
    path: '',
    levelPath: '1',
    icon: 'ri-dashboard-line',
    children: [
      {
        id: 11,
        type: 2,
        parent_id: 1,
        levelPath: '1-11',
        name: '主控台',
        path: '/dashboard/console',
        defaultActive: true,
      },
      {
        id: 12,
        type: 2,
        parent_id: 1,
        levelPath: '1-12',
        name: '监控台',
        path: '/dashboard/monitor',
      },
      {
        id: 13,
        type: 2,
        parent_id: 1,
        levelPath: '1-13',
        name: '工作台',
        path: '/dashboard/workplace',
      },
    ],
  },
  {
    id: 2,
    type: 1,
    parent_id: null,
    name: 'Component',
    path: '',
    levelPath: '2',
    icon: 'ri-dashboard-line',
    children: [
      {
        id: 21,
        type: 2,
        parent_id: null,
        name: 'Button',
        path: '/components/button',
        levelPath: '2-21',
        icon: 'ri-dashboard-line',
      },
      {
        id: 22,
        type: 2,
        parent_id: null,
        name: 'Form',
        path: '/components/form',
        levelPath: '2-22',
        icon: 'ri-dashboard-line',
      },
      {
        id: 23,
        type: 2,
        parent_id: null,
        name: 'Table',
        path: '/components/table',
        levelPath: '2-22',
        icon: 'ri-dashboard-line',
      },
      {
        id: 24,
        type: 2,
        parent_id: null,
        name: 'Loading',
        path: '/components/loading',
        levelPath: '2-24',
        icon: 'ri-dashboard-line',
      },
    ],
  },
  {
    id: 3,
    type: 1,
    parent_id: null,
    name: 'Feature',
    path: '',
    levelPath: '3',
    icon: 'ri-dashboard-line',
    children: [],
  },
  {
    id: 5,
    type: 1,
    parent_id: null,
    name: 'Exception',
    path: '',
    levelPath: '5',
    icon: 'ri-dashboard-line',
    children: [
      {
        id: 51,
        type: 2,
        parent_id: null,
        name: '200(Ok)',
        path: '/exception/ok',
        levelPath: '5-51',
        icon: 'ri-dashboard-line',
      },
      {
        id: 52,
        type: 2,
        parent_id: null,
        name: '401(Unauthorized)',
        path: '/exception/unauthorized',
        levelPath: '5-52',
        icon: 'ri-dashboard-line',
      },
      {
        id: 53,
        type: 2,
        parent_id: null,
        name: '403(Forbidden)',
        path: '/exception/forbidden',
        levelPath: '5-53',
        icon: 'ri-dashboard-line',
      },
      {
        id: 54,
        type: 2,
        parent_id: null,
        name: '404(Not Found)',
        path: '/exception/notFound',
        levelPath: '5-54',
        icon: 'ri-dashboard-line',
      },
      {
        id: 55,
        type: 2,
        parent_id: null,
        name: '500(Servier Error)',
        path: '/exception/serverError',
        levelPath: '5-55',
        icon: 'ri-dashboard-line',
      },
    ],
  },
  {
    id: 6,
    type: 1,
    parent_id: null,
    name: 'Directive',
    path: '',
    levelPath: '6',
    icon: 'ri-dashboard-line',
    children: [
      {
        id: 61,
        type: 2,
        parent_id: null,
        name: 'clickOutside',
        path: '/directive/clickOutside',
        levelPath: '6-61',
        icon: 'ri-dashboard-line',
      },
      {
        id: 62,
        type: 2,
        parent_id: null,
        name: 'debounce',
        path: '/directive/debounce',
        levelPath: '6-62',
        icon: 'ri-dashboard-line',
      },
      {
        id: 63,
        type: 2,
        parent_id: null,
        name: 'permission',
        path: '/directive/permission',
        levelPath: '6-63',
        icon: 'ri-dashboard-line',
      },
      {
        id: 64,
        type: 2,
        parent_id: null,
        name: 'longPress',
        path: '/directive/longPress',
        levelPath: '6-64',
        icon: 'ri-dashboard-line',
      },
      {
        id: 65,
        type: 2,
        parent_id: null,
        name: 'copy',
        path: '/directive/copy',
        levelPath: '6-65',
        icon: 'ri-dashboard-line',
      },
      {
        id: 66,
        type: 2,
        parent_id: null,
        name: 'loading',
        path: '/directive/loading',
        levelPath: '6-66',
        icon: 'ri-dashboard-line',
      },
      {
        id: 67,
        type: 2,
        parent_id: null,
        name: 'lazyLoad',
        path: '/directive/lazyLoad',
        levelPath: '6-67',
        icon: 'ri-dashboard-line',
      },
      {
        id: 68,
        type: 2,
        parent_id: null,
        name: 'draggable',
        path: '/directive/draggable',
        levelPath: '6-68',
        icon: 'ri-dashboard-line',
      },
      {
        id: 69,
        type: 2,
        parent_id: null,
        name: 'waterMarker',
        path: '/directive/waterMarker',
        levelPath: '6-68',
        icon: 'ri-dashboard-line',
      },
    ],
  },
];
