import type {
  ModelCapability,
  ModelItem,
  ModelPageConfig,
  ModelProvider,
  ModelProviderOption,
} from './types'

export const providerOptions: ModelProviderOption[] = [
  {
    value: 'openai',
    label: 'OpenAI',
    icon: 'i-lucide:sparkles',
    accent: '#2563EB',
    softBackground: '#DBEAFE',
    protocol: 'openai-compatible',
    endpoint: 'https://api.openai.com/v1',
  },
  {
    value: 'anthropic',
    label: 'Anthropic',
    icon: 'i-lucide:brain',
    accent: '#C2410C',
    softBackground: '#FFEDD5',
    protocol: 'anthropic',
    endpoint: 'https://api.anthropic.com/v1',
  },
  {
    value: 'zhipu',
    label: '智谱 AI',
    icon: 'i-lucide:layers-3',
    accent: '#4F46E5',
    softBackground: '#E0E7FF',
    protocol: 'openai-compatible',
    endpoint: 'https://open.bigmodel.cn/api/paas/v4',
  },
  {
    value: 'moonshot',
    label: 'Moonshot',
    icon: 'i-lucide:moon',
    accent: '#7C3AED',
    softBackground: '#EDE9FE',
    protocol: 'openai-compatible',
    endpoint: 'https://api.moonshot.cn/v1',
  },
  {
    value: 'deepseek',
    label: 'DeepSeek',
    icon: 'i-lucide:fish',
    accent: '#0891B2',
    softBackground: '#CFFAFE',
    protocol: 'openai-compatible',
    endpoint: 'https://api.deepseek.com/v1',
  },
  {
    value: 'google',
    label: 'Google',
    icon: 'i-lucide:gem',
    accent: '#16A34A',
    softBackground: '#DCFCE7',
    protocol: 'google-generative-ai',
    endpoint: 'https://generativelanguage.googleapis.com/v1beta',
  },
  {
    value: 'qwen',
    label: '通义千问',
    icon: 'i-lucide:cloud-cog',
    accent: '#EA580C',
    softBackground: '#FFEDD5',
    protocol: 'openai-compatible',
    endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  },
  {
    value: 'custom',
    label: '自定义供应商',
    icon: 'i-lucide:blocks',
    accent: '#475569',
    softBackground: '#E2E8F0',
    protocol: 'openai-compatible',
    endpoint: 'https://api.example.com/v1',
  },
]

export const protocolOptions = [
  { label: 'OpenAI Compatible', value: 'openai-compatible' },
  { label: 'Anthropic Messages', value: 'anthropic' },
  { label: 'Google Generative AI', value: 'google-generative-ai' },
]

export const capabilityOptions: Array<{
  label: string
  value: ModelCapability
}> = [
  { label: '对话', value: 'chat' },
  { label: '视觉理解', value: 'vision' },
  { label: '函数调用', value: 'function-call' },
  { label: 'JSON 输出', value: 'json' },
  { label: '深度推理', value: 'reasoning' },
]

export const modelPageConfig: ModelPageConfig = {
  title: '模型列表',
  subtitle:
    '统一管理 Agent、Chat 和工作流可调用的 LLM，集中维护供应商、协议、密钥和上下文参数。',
  icon: 'i-lucide:cpu',
  createText: '新建模型',
  searchPlaceholder: '搜索模型名称、Model ID、供应商或能力',
  emptyText: '没有符合条件的模型',
  totalText: '模型',
  activeText: '已启用',
  configuredText: '已配置密钥',
  statusLabels: {
    online: '已启用',
    draft: '草稿',
    offline: '已停用',
  },
}

export const modelResources: ModelItem[] = [
  {
    id: 'model-gpt-4o',
    kind: 'llm-model',
    provider: 'openai',
    providerName: 'OpenAI',
    name: 'GPT-4o',
    modelId: 'gpt-4o',
    description: '通用多模态旗舰模型，适合复杂对话、视觉理解和工具调用。',
    protocol: 'openai-compatible',
    endpoint: 'https://api.openai.com/v1',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    capabilities: ['chat', 'vision', 'function-call', 'json'],
    inputPrice: 2.5,
    outputPrice: 10,
    status: 'online',
    apiKeyConfigured: true,
    apiKeyMasked: 'sk-proj-••••••••9A2F',
    monthlyCalls: '42.8k',
    avgLatency: '1.7s',
    createdAt: '2026-06-12 09:20',
    updatedAt: '2026-08-16 14:32',
  },
  {
    id: 'model-gpt-4o-mini',
    kind: 'llm-model',
    provider: 'openai',
    providerName: 'OpenAI',
    name: 'GPT-4o mini',
    modelId: 'gpt-4o-mini',
    description: '高性价比轻量模型，适合分类、摘要、提取和批量自动化任务。',
    protocol: 'openai-compatible',
    endpoint: 'https://api.openai.com/v1',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    capabilities: ['chat', 'vision', 'function-call', 'json'],
    inputPrice: 0.15,
    outputPrice: 0.6,
    status: 'online',
    apiKeyConfigured: true,
    apiKeyMasked: 'sk-proj-••••••••9A2F',
    monthlyCalls: '86.2k',
    avgLatency: '0.9s',
    createdAt: '2026-06-12 09:32',
    updatedAt: '2026-08-15 11:08',
  },
  {
    id: 'model-claude-sonnet',
    kind: 'llm-model',
    provider: 'anthropic',
    providerName: 'Anthropic',
    name: 'Claude 3.7 Sonnet',
    modelId: 'claude-3-7-sonnet-latest',
    description: '擅长长文本分析、代码生成和结构化推理的企业级模型。',
    protocol: 'anthropic',
    endpoint: 'https://api.anthropic.com/v1',
    contextWindow: 200000,
    maxOutputTokens: 128000,
    capabilities: ['chat', 'vision', 'function-call', 'reasoning'],
    inputPrice: 3,
    outputPrice: 15,
    status: 'online',
    apiKeyConfigured: true,
    apiKeyMasked: 'sk-ant-••••••••72C1',
    monthlyCalls: '18.4k',
    avgLatency: '2.4s',
    createdAt: '2026-06-18 16:40',
    updatedAt: '2026-08-14 17:50',
  },
  {
    id: 'model-glm-4-plus',
    kind: 'llm-model',
    provider: 'zhipu',
    providerName: '智谱 AI',
    name: 'GLM-4-Plus',
    modelId: 'glm-4-plus',
    description: '面向中文业务场景优化，适合企业知识问答和智能客服。',
    protocol: 'openai-compatible',
    endpoint: 'https://open.bigmodel.cn/api/paas/v4',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    capabilities: ['chat', 'function-call', 'json'],
    inputPrice: 0.7,
    outputPrice: 0.7,
    status: 'online',
    apiKeyConfigured: true,
    apiKeyMasked: '••••••••••••4F9D',
    monthlyCalls: '31.6k',
    avgLatency: '1.2s',
    createdAt: '2026-06-22 10:15',
    updatedAt: '2026-08-13 09:44',
  },
  {
    id: 'model-kimi-k2',
    kind: 'llm-model',
    provider: 'moonshot',
    providerName: 'Moonshot',
    name: 'Kimi K2',
    modelId: 'kimi-k2-0711-preview',
    description: '超长上下文模型，适合代码仓库阅读、文档审阅和复杂任务拆解。',
    protocol: 'openai-compatible',
    endpoint: 'https://api.moonshot.cn/v1',
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    capabilities: ['chat', 'function-call', 'reasoning'],
    inputPrice: 4,
    outputPrice: 16,
    status: 'draft',
    apiKeyConfigured: true,
    apiKeyMasked: 'sk-••••••••B812',
    monthlyCalls: '—',
    avgLatency: '—',
    createdAt: '2026-08-09 15:12',
    updatedAt: '2026-08-16 10:26',
  },
  {
    id: 'model-deepseek-v3',
    kind: 'llm-model',
    provider: 'deepseek',
    providerName: 'DeepSeek',
    name: 'DeepSeek V3',
    modelId: 'deepseek-chat',
    description: '适用于高吞吐对话和代码任务的通用模型，成本控制友好。',
    protocol: 'openai-compatible',
    endpoint: 'https://api.deepseek.com/v1',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    capabilities: ['chat', 'function-call', 'json'],
    inputPrice: 0.27,
    outputPrice: 1.1,
    status: 'online',
    apiKeyConfigured: true,
    apiKeyMasked: 'sk-••••••••F21A',
    monthlyCalls: '96.5k',
    avgLatency: '1.1s',
    createdAt: '2026-06-10 11:45',
    updatedAt: '2026-08-12 16:20',
  },
  {
    id: 'model-gemini-pro',
    kind: 'llm-model',
    provider: 'google',
    providerName: 'Google',
    name: 'Gemini 2.5 Pro',
    modelId: 'gemini-2.5-pro',
    description: '支持长上下文和多模态输入，适合研究分析与复杂推理。',
    protocol: 'google-generative-ai',
    endpoint: 'https://generativelanguage.googleapis.com/v1beta',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    capabilities: ['chat', 'vision', 'function-call', 'reasoning'],
    inputPrice: 1.25,
    outputPrice: 10,
    status: 'offline',
    apiKeyConfigured: false,
    apiKeyMasked: '未配置',
    monthlyCalls: '—',
    avgLatency: '—',
    createdAt: '2026-07-02 14:28',
    updatedAt: '2026-08-08 13:12',
  },
  {
    id: 'model-qwen-max',
    kind: 'llm-model',
    provider: 'qwen',
    providerName: '通义千问',
    name: 'Qwen-Max',
    modelId: 'qwen-max',
    description: '中文和企业知识场景表现稳定，支持工具调用与结构化输出。',
    protocol: 'openai-compatible',
    endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    contextWindow: 32768,
    maxOutputTokens: 8192,
    capabilities: ['chat', 'function-call', 'json'],
    inputPrice: 2.4,
    outputPrice: 9.6,
    status: 'online',
    apiKeyConfigured: true,
    apiKeyMasked: 'sk-••••••••AC30',
    monthlyCalls: '24.1k',
    avgLatency: '1.5s',
    createdAt: '2026-07-05 09:50',
    updatedAt: '2026-08-11 18:06',
  },
  {
    id: 'model-deepseek-r1',
    kind: 'llm-model',
    provider: 'deepseek',
    providerName: 'DeepSeek',
    name: 'DeepSeek R1',
    modelId: 'deepseek-reasoner',
    description: '推理模型，适合复杂规划、代码分析和需要多步验证的任务。',
    protocol: 'openai-compatible',
    endpoint: 'https://api.deepseek.com/v1',
    contextWindow: 128000,
    maxOutputTokens: 65536,
    capabilities: ['chat', 'reasoning', 'json'],
    inputPrice: 0.55,
    outputPrice: 2.19,
    status: 'draft',
    apiKeyConfigured: true,
    apiKeyMasked: 'sk-••••••••F21A',
    monthlyCalls: '—',
    avgLatency: '—',
    createdAt: '2026-07-18 16:36',
    updatedAt: '2026-08-10 10:42',
  },
  {
    id: 'model-custom-internal',
    kind: 'llm-model',
    provider: 'custom',
    providerName: '企业内部模型网关',
    name: 'Enterprise Chat 32B',
    modelId: 'enterprise-chat-32b',
    description: '通过企业内部网关接入的私有模型，数据不离开内网。',
    protocol: 'openai-compatible',
    endpoint: 'https://llm-gateway.intra.example.com/v1',
    contextWindow: 65536,
    maxOutputTokens: 8192,
    capabilities: ['chat', 'function-call', 'json'],
    inputPrice: 0,
    outputPrice: 0,
    status: 'online',
    apiKeyConfigured: true,
    apiKeyMasked: 'gw-••••••••8820',
    monthlyCalls: '15.7k',
    avgLatency: '0.7s',
    createdAt: '2026-07-24 11:20',
    updatedAt: '2026-08-07 15:08',
  },
]

export function getProviderMeta(provider: ModelProvider) {
  return (
    providerOptions.find((option) => option.value === provider) ??
    providerOptions[providerOptions.length - 1]
  )
}

export function getProviderLabel(provider: ModelProvider) {
  return getProviderMeta(provider).label
}

export function getCapabilityLabel(capability: ModelCapability) {
  return (
    capabilityOptions.find((option) => option.value === capability)?.label ??
    capability
  )
}

export function formatTokenWindow(value: number) {
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`
  if (value >= 1_000) return `${Math.round(value / 1_000)}K`
  return String(value)
}
